/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.AdminUpdateUserResponseDto
import com.cashful.model.SessionUserDto

class AdminUpdateUserResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminUpdateUserResponseDto
        //val modelInstance = AdminUpdateUserResponseDto()

        // to test the property `user` - User updated successfully
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

    }
}
