/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.AdminSetUserPasswordResponseDto

class AdminSetUserPasswordResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminSetUserPasswordResponseDto
        //val modelInstance = AdminSetUserPasswordResponseDto()

        // to test the property `success` - User password set successfully
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

    }
}
