/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.ChangeEmailDto

class ChangeEmailDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChangeEmailDto
        //val modelInstance = ChangeEmailDto()

        // to test the property `newEmail` - The new email address to set must be a valid email address
        should("test newEmail") {
            // uncomment below to test the property
            //modelInstance.newEmail shouldBe ("TODO")
        }

        // to test the property `callbackURL` - The URL to redirect to after email verification
        should("test callbackURL") {
            // uncomment below to test the property
            //modelInstance.callbackURL shouldBe ("TODO")
        }

    }
}
