/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.CheckoutSessionConfirmResponseDto

class CheckoutSessionConfirmResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutSessionConfirmResponseDto
        //val modelInstance = CheckoutSessionConfirmResponseDto()

        // to test the property `sessionId`
        should("test sessionId") {
            // uncomment below to test the property
            //modelInstance.sessionId shouldBe ("TODO")
        }

        // to test the property `paymentIntentId`
        should("test paymentIntentId") {
            // uncomment below to test the property
            //modelInstance.paymentIntentId shouldBe ("TODO")
        }

        // to test the property `iveriParams`
        should("test iveriParams") {
            // uncomment below to test the property
            //modelInstance.iveriParams shouldBe ("TODO")
        }

        // to test the property `iVeri3dsEndpoint`
        should("test iVeri3dsEndpoint") {
            // uncomment below to test the property
            //modelInstance.iVeri3dsEndpoint shouldBe ("TODO")
        }

    }
}
