/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.CreateApiKeyResponseDto
import com.cashful.model.ApiKey

class CreateApiKeyResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateApiKeyResponseDto
        //val modelInstance = CreateApiKeyResponseDto()

        // to test the property `apiKey` - API key created successfully
        should("test apiKey") {
            // uncomment below to test the property
            //modelInstance.apiKey shouldBe ("TODO")
        }

    }
}
