/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.CreatePaymentIntentDto

class CreatePaymentIntentDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreatePaymentIntentDto
        //val modelInstance = CreatePaymentIntentDto()

        // to test the property `amount` - The amount to charge in the smallest currency unit (cents)
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `currency` - The three-letter ISO 4217 currency code
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `merchantId` - The ID of the merchant. If omitted, defaults to the authenticated merchant.
        should("test merchantId") {
            // uncomment below to test the property
            //modelInstance.merchantId shouldBe ("TODO")
        }

        // to test the property `customerId` - The unique identifier of the customer. Optional for payment intents that don't require a customer.
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `paymentMethodId` - The unique identifier of the payment method. Optional if payment method will be collected later.
        should("test paymentMethodId") {
            // uncomment below to test the property
            //modelInstance.paymentMethodId shouldBe ("TODO")
        }

        // to test the property `mode` - The mode of the payment intent
        should("test mode") {
            // uncomment below to test the property
            //modelInstance.mode shouldBe ("TODO")
        }

        // to test the property `description` - Optional description for the payment
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `metadata` - Optional custom metadata
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `idempotencyKey` - A unique key to prevent duplicate charges. If not provided, one will be generated.
        should("test idempotencyKey") {
            // uncomment below to test the property
            //modelInstance.idempotencyKey shouldBe ("TODO")
        }

        // to test the property `expiresAt` - When the payment intent expires. Defaults to 24 hours from creation.
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

    }
}
