/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.CreateCheckoutSessionDto
import com.cashful.model.HostedCheckoutConfigDto
import com.cashful.model.LineItemDto

class CreateCheckoutSessionDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateCheckoutSessionDto
        //val modelInstance = CreateCheckoutSessionDto()

        // to test the property `currency` - The three-letter ISO 4217 currency code
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `metadata` - Optional custom metadata
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `merchantId` - The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
        should("test merchantId") {
            // uncomment below to test the property
            //modelInstance.merchantId shouldBe ("TODO")
        }

        // to test the property `customerId` - The unique identifier of the customer
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `productId` - The unique identifier of the product
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `successUrl` - The URL to redirect to on successful payment
        should("test successUrl") {
            // uncomment below to test the property
            //modelInstance.successUrl shouldBe ("TODO")
        }

        // to test the property `failureUrl` - The URL to redirect to on failure
        should("test failureUrl") {
            // uncomment below to test the property
            //modelInstance.failureUrl shouldBe ("TODO")
        }

        // to test the property `cancelUrl` - The URL to redirect to on cancel
        should("test cancelUrl") {
            // uncomment below to test the property
            //modelInstance.cancelUrl shouldBe ("TODO")
        }

        // to test the property `lineItems` - Array of line items for the checkout
        should("test lineItems") {
            // uncomment below to test the property
            //modelInstance.lineItems shouldBe ("TODO")
        }

        // to test the property `totalAmount` - The total amount in the smallest currency unit
        should("test totalAmount") {
            // uncomment below to test the property
            //modelInstance.totalAmount shouldBe ("TODO")
        }

        // to test the property `mode` - The checkout mode (e.g., 'payment')
        should("test mode") {
            // uncomment below to test the property
            //modelInstance.mode shouldBe ("TODO")
        }

        // to test the property `hostedCheckoutConfig` - Configuration for the hosted checkout page
        should("test hostedCheckoutConfig") {
            // uncomment below to test the property
            //modelInstance.hostedCheckoutConfig shouldBe ("TODO")
        }

    }
}
