/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.CustomerStatsDto

class CustomerStatsDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomerStatsDto
        //val modelInstance = CustomerStatsDto()

        // to test the property `daily` - New customers in the last 24 hours
        should("test daily") {
            // uncomment below to test the property
            //modelInstance.daily shouldBe ("TODO")
        }

        // to test the property `weekly` - New customers in the last 7 days
        should("test weekly") {
            // uncomment below to test the property
            //modelInstance.weekly shouldBe ("TODO")
        }

        // to test the property `monthly` - New customers in the last 30 days
        should("test monthly") {
            // uncomment below to test the property
            //modelInstance.monthly shouldBe ("TODO")
        }

    }
}
