/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.DailyBreakdownDto

class DailyBreakdownDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DailyBreakdownDto
        //val modelInstance = DailyBreakdownDto()

        // to test the property `date` - The date for this breakdown (ISO string)
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `count` - Count of transactions on this day
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `sum` - Sum of transaction amounts on this day
        should("test sum") {
            // uncomment below to test the property
            //modelInstance.sum shouldBe ("TODO")
        }

    }
}
