/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.EvervaultEncryptedCardDto

class EvervaultEncryptedCardDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EvervaultEncryptedCardDto
        //val modelInstance = EvervaultEncryptedCardDto()

        // to test the property `PAN` - Encrypted Primary Account Number (PAN)
        should("test PAN") {
            // uncomment below to test the property
            //modelInstance.PAN shouldBe ("TODO")
        }

        // to test the property `expiryDate` - Encrypted card expiry date
        should("test expiryDate") {
            // uncomment below to test the property
            //modelInstance.expiryDate shouldBe ("TODO")
        }

        // to test the property `cardSecurityCode` - Encrypted card security code (CVV)
        should("test cardSecurityCode") {
            // uncomment below to test the property
            //modelInstance.cardSecurityCode shouldBe ("TODO")
        }

        // to test the property `cardholderName` - Encrypted cardholder name
        should("test cardholderName") {
            // uncomment below to test the property
            //modelInstance.cardholderName shouldBe ("TODO")
        }

    }
}
