/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.HostedCheckoutConfigDto

class HostedCheckoutConfigDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HostedCheckoutConfigDto
        //val modelInstance = HostedCheckoutConfigDto()

        // to test the property `merchantId` - Merchant ID
        should("test merchantId") {
            // uncomment below to test the property
            //modelInstance.merchantId shouldBe ("TODO")
        }

        // to test the property `merchantAlias` - Merchant alias
        should("test merchantAlias") {
            // uncomment below to test the property
            //modelInstance.merchantAlias shouldBe ("TODO")
        }

        // to test the property `merchantLegalName` - Merchant legal name
        should("test merchantLegalName") {
            // uncomment below to test the property
            //modelInstance.merchantLegalName shouldBe ("TODO")
        }

        // to test the property `merchantAvatarTextPlaceholder` - Merchant avatar text placeholder
        should("test merchantAvatarTextPlaceholder") {
            // uncomment below to test the property
            //modelInstance.merchantAvatarTextPlaceholder shouldBe ("TODO")
        }

        // to test the property `merchantAvatarUrl` - Merchant avatar URL
        should("test merchantAvatarUrl") {
            // uncomment below to test the property
            //modelInstance.merchantAvatarUrl shouldBe ("TODO")
        }

        // to test the property `requireContact` - Require contact
        should("test requireContact") {
            // uncomment below to test the property
            //modelInstance.requireContact shouldBe ("TODO")
        }

        // to test the property `requireAddress` - Require address
        should("test requireAddress") {
            // uncomment below to test the property
            //modelInstance.requireAddress shouldBe ("TODO")
        }

        // to test the property `taxRate` - Tax rate
        should("test taxRate") {
            // uncomment below to test the property
            //modelInstance.taxRate shouldBe ("TODO")
        }

        // to test the property `embedMode` - Embed mode
        should("test embedMode") {
            // uncomment below to test the property
            //modelInstance.embedMode shouldBe ("TODO")
        }

        // to test the property `embedOrigin` - Embed origin
        should("test embedOrigin") {
            // uncomment below to test the property
            //modelInstance.embedOrigin shouldBe ("TODO")
        }

        // to test the property `methods` - Enabled payment methods
        should("test methods") {
            // uncomment below to test the property
            //modelInstance.methods shouldBe ("TODO")
        }

    }
}
