/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.InternalAnalyticsInsightsDto

class InternalAnalyticsInsightsDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InternalAnalyticsInsightsDto
        //val modelInstance = InternalAnalyticsInsightsDto()

        // to test the property `organizations` - Total number of organizations on the platform
        should("test organizations") {
            // uncomment below to test the property
            //modelInstance.organizations shouldBe ("TODO")
        }

        // to test the property `customers` - Total number of active customers across all organizations
        should("test customers") {
            // uncomment below to test the property
            //modelInstance.customers shouldBe ("TODO")
        }

        // to test the property `savedPaymentMethods` - Total number of saved payment methods across all customers (non-deleted)
        should("test savedPaymentMethods") {
            // uncomment below to test the property
            //modelInstance.savedPaymentMethods shouldBe ("TODO")
        }

        // to test the property `transactions` - Total number of transactions across all organizations
        should("test transactions") {
            // uncomment below to test the property
            //modelInstance.transactions shouldBe ("TODO")
        }

        // to test the property `totalAvailableBalance` - Sum of available merchant balances across all organizations (in cents/smallest unit)
        should("test totalAvailableBalance") {
            // uncomment below to test the property
            //modelInstance.totalAvailableBalance shouldBe ("TODO")
        }

        // to test the property `totalPendingBalance` - Sum of pending merchant balances across all organizations (in cents/smallest unit)
        should("test totalPendingBalance") {
            // uncomment below to test the property
            //modelInstance.totalPendingBalance shouldBe ("TODO")
        }

    }
}
