/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.InviteMemberResponseDto

class InviteMemberResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InviteMemberResponseDto
        //val modelInstance = InviteMemberResponseDto()

        // to test the property `invitation` - Member invited successfully
        should("test invitation") {
            // uncomment below to test the property
            //modelInstance.invitation shouldBe ("TODO")
        }

    }
}
