/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.IsUsernameAvailableResponseDto

class IsUsernameAvailableResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IsUsernameAvailableResponseDto
        //val modelInstance = IsUsernameAvailableResponseDto()

        // to test the property `available` - Whether username is available
        should("test available") {
            // uncomment below to test the property
            //modelInstance.available shouldBe ("TODO")
        }

    }
}
