/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.IsUsernameAvailableDto

class IsUsernameAvailableDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IsUsernameAvailableDto
        //val modelInstance = IsUsernameAvailableDto()

        // to test the property `username` - The username to check availability for
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

    }
}
