/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.LinkedAccountDto

class LinkedAccountDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LinkedAccountDto
        //val modelInstance = LinkedAccountDto()

        // to test the property `id` - Unique identifier
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `accountId` - Account ID
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `providerId` - Provider ID (e.g., google, github)
        should("test providerId") {
            // uncomment below to test the property
            //modelInstance.providerId shouldBe ("TODO")
        }

        // to test the property `userId` - User ID
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `createdAt` - Creation timestamp
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - Last update timestamp
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `accessToken` - Access token
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `refreshToken` - Refresh token
        should("test refreshToken") {
            // uncomment below to test the property
            //modelInstance.refreshToken shouldBe ("TODO")
        }

        // to test the property `idToken` - ID token
        should("test idToken") {
            // uncomment below to test the property
            //modelInstance.idToken shouldBe ("TODO")
        }

        // to test the property `accessTokenExpiresAt` - Access token expires at
        should("test accessTokenExpiresAt") {
            // uncomment below to test the property
            //modelInstance.accessTokenExpiresAt shouldBe ("TODO")
        }

        // to test the property `refreshTokenExpiresAt` - Refresh token expires at
        should("test refreshTokenExpiresAt") {
            // uncomment below to test the property
            //modelInstance.refreshTokenExpiresAt shouldBe ("TODO")
        }

        // to test the property `scope` - Scope
        should("test scope") {
            // uncomment below to test the property
            //modelInstance.scope shouldBe ("TODO")
        }

        // to test the property `password` - Password
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

    }
}
