/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.LinkSocialResponseDto

class LinkSocialResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LinkSocialResponseDto
        //val modelInstance = LinkSocialResponseDto()

        // to test the property `success` - Social account linked successfully
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property `account` - Linked account details
        should("test account") {
            // uncomment below to test the property
            //modelInstance.account shouldBe ("TODO")
        }

    }
}
