/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.ListCustomerTransactionsResponseDto
import com.cashful.model.CustomerTransactionDto
import com.cashful.model.PaginationResponseDto

class ListCustomerTransactionsResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListCustomerTransactionsResponseDto
        //val modelInstance = ListCustomerTransactionsResponseDto()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `pagination`
        should("test pagination") {
            // uncomment below to test the property
            //modelInstance.pagination shouldBe ("TODO")
        }

    }
}
