/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.ResetPhonePasswordDto

class ResetPhonePasswordDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResetPhonePasswordDto
        //val modelInstance = ResetPhonePasswordDto()

        // to test the property `phoneNumber` - The phone number
        should("test phoneNumber") {
            // uncomment below to test the property
            //modelInstance.phoneNumber shouldBe ("TODO")
        }

        // to test the property `code` - The OTP code received
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `newPassword` - The new password
        should("test newPassword") {
            // uncomment below to test the property
            //modelInstance.newPassword shouldBe ("TODO")
        }

    }
}
