/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.RetrieveMultipleProductsDto

class RetrieveMultipleProductsDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RetrieveMultipleProductsDto
        //val modelInstance = RetrieveMultipleProductsDto()

        // to test the property `ids` - Max 50 IDs of the products to retrieve
        should("test ids") {
            // uncomment below to test the property
            //modelInstance.ids shouldBe ("TODO")
        }

    }
}
