/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.RevokeSessionDto

class RevokeSessionDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RevokeSessionDto
        //val modelInstance = RevokeSessionDto()

        // to test the property `sessionId` - The session ID to revoke
        should("test sessionId") {
            // uncomment below to test the property
            //modelInstance.sessionId shouldBe ("TODO")
        }

    }
}
