/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.SendEmail200Response

class SendEmail200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SendEmail200Response
        //val modelInstance = SendEmail200Response()

        // to test the property `messageId` - Email message ID
        should("test messageId") {
            // uncomment below to test the property
            //modelInstance.messageId shouldBe ("TODO")
        }

    }
}
