/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.SignUpResponseDto
import com.cashful.model.SessionUserDto

class SignUpResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SignUpResponseDto
        //val modelInstance = SignUpResponseDto()

        // to test the property `user` - User object created successfully
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `token` - Authentication token for the session
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

    }
}
