/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.SignInDto

class SignInDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SignInDto
        //val modelInstance = SignInDto()

        // to test the property `email` - The email address of the user
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `password` - The password for the user account
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `callbackURL` - The URL to use for email verification callback
        should("test callbackURL") {
            // uncomment below to test the property
            //modelInstance.callbackURL shouldBe ("TODO")
        }

        // to test the property `rememberMe` - If this is false, the session will not be remembered. Default is `true`.
        should("test rememberMe") {
            // uncomment below to test the property
            //modelInstance.rememberMe shouldBe ("TODO")
        }

    }
}
