/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.UnlinkAccountDto

class UnlinkAccountDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UnlinkAccountDto
        //val modelInstance = UnlinkAccountDto()

        // to test the property `provider` - The social provider to unlink
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `accountId` - The provider account ID to unlink
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

    }
}
