/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.UpdateWebhookEndpointDto

class UpdateWebhookEndpointDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateWebhookEndpointDto
        //val modelInstance = UpdateWebhookEndpointDto()

        // to test the property `url` - The URL where webhook events will be sent
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `events` - Array of event types to listen for
        should("test events") {
            // uncomment below to test the property
            //modelInstance.events shouldBe ("TODO")
        }

        // to test the property `active` - Whether the webhook endpoint is active
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `metadata` - Optional custom metadata
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
