/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.UpdateFileDto

class UpdateFileDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateFileDto
        //val modelInstance = UpdateFileDto()

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `isPublic`
        should("test isPublic") {
            // uncomment below to test the property
            //modelInstance.isPublic shouldBe ("TODO")
        }

        // to test the property `relatedEntityId`
        should("test relatedEntityId") {
            // uncomment below to test the property
            //modelInstance.relatedEntityId shouldBe ("TODO")
        }

        // to test the property `relatedEntityType`
        should("test relatedEntityType") {
            // uncomment below to test the property
            //modelInstance.relatedEntityType shouldBe ("TODO")
        }

    }
}
