/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.UpdateOrganizationResponseDto
import com.cashful.model.OrganizationDto

class UpdateOrganizationResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateOrganizationResponseDto
        //val modelInstance = UpdateOrganizationResponseDto()

        // to test the property `organization` - Organization updated successfully
        should("test organization") {
            // uncomment below to test the property
            //modelInstance.organization shouldBe ("TODO")
        }

    }
}
