/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.model.VerifyEmailResponseDto
import com.cashful.model.SessionUserDto

class VerifyEmailResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VerifyEmailResponseDto
        //val modelInstance = VerifyEmailResponseDto()

        // to test the property `user` - User object
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `status` - Indicates if email was verified successfully
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
