/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.cashful.kotlin.sdk.model.BalanceHistoryResponseDto
import com.cashful.kotlin.sdk.model.ErrorResponseDto
import com.cashful.kotlin.sdk.model.MerchantBalanceResponseDto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.cashful.kotlin.sdk.infrastructure.ApiClient
import com.cashful.kotlin.sdk.infrastructure.ApiResponse
import com.cashful.kotlin.sdk.infrastructure.ClientException
import com.cashful.kotlin.sdk.infrastructure.ClientError
import com.cashful.kotlin.sdk.infrastructure.ServerException
import com.cashful.kotlin.sdk.infrastructure.ServerError
import com.cashful.kotlin.sdk.infrastructure.MultiValueMap
import com.cashful.kotlin.sdk.infrastructure.PartConfig
import com.cashful.kotlin.sdk.infrastructure.RequestConfig
import com.cashful.kotlin.sdk.infrastructure.RequestMethod
import com.cashful.kotlin.sdk.infrastructure.ResponseType
import com.cashful.kotlin.sdk.infrastructure.Success
import com.cashful.kotlin.sdk.infrastructure.toMultiValue

class BalanceApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:3000")
        }
    }

    /**
     * GET /api/canary/balance/history
     * List Merchant Balance History
     * A full ledger of all transactions, fees, and payouts for the merchant&#39;s master account.
     * @param merchantId The ID of the merchant. This parameter is required.
     * @param transactionType Filter by transaction type (e.g., \&quot;credit\&quot;, \&quot;debit\&quot;, \&quot;fee\&quot;, \&quot;payout\&quot;) (optional)
     * @param endDate Filter transactions until this date (ISO 8601 format) (optional)
     * @param startDate Filter transactions from this date (ISO 8601 format) (optional)
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @return BalanceHistoryResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getBalanceHistory(merchantId: kotlin.String, transactionType: kotlin.Any? = null, endDate: kotlin.Any? = null, startDate: kotlin.Any? = null, limit: java.math.BigDecimal? = null, offset: java.math.BigDecimal? = null) : BalanceHistoryResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = getBalanceHistoryWithHttpInfo(merchantId = merchantId, transactionType = transactionType, endDate = endDate, startDate = startDate, limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BalanceHistoryResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/canary/balance/history
     * List Merchant Balance History
     * A full ledger of all transactions, fees, and payouts for the merchant&#39;s master account.
     * @param merchantId The ID of the merchant. This parameter is required.
     * @param transactionType Filter by transaction type (e.g., \&quot;credit\&quot;, \&quot;debit\&quot;, \&quot;fee\&quot;, \&quot;payout\&quot;) (optional)
     * @param endDate Filter transactions until this date (ISO 8601 format) (optional)
     * @param startDate Filter transactions from this date (ISO 8601 format) (optional)
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @return ApiResponse<BalanceHistoryResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getBalanceHistoryWithHttpInfo(merchantId: kotlin.String, transactionType: kotlin.Any?, endDate: kotlin.Any?, startDate: kotlin.Any?, limit: java.math.BigDecimal?, offset: java.math.BigDecimal?) : ApiResponse<BalanceHistoryResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getBalanceHistoryRequestConfig(merchantId = merchantId, transactionType = transactionType, endDate = endDate, startDate = startDate, limit = limit, offset = offset)

        return@withContext request<Unit, BalanceHistoryResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getBalanceHistory
     *
     * @param merchantId The ID of the merchant. This parameter is required.
     * @param transactionType Filter by transaction type (e.g., \&quot;credit\&quot;, \&quot;debit\&quot;, \&quot;fee\&quot;, \&quot;payout\&quot;) (optional)
     * @param endDate Filter transactions until this date (ISO 8601 format) (optional)
     * @param startDate Filter transactions from this date (ISO 8601 format) (optional)
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @return RequestConfig
     */
    fun getBalanceHistoryRequestConfig(merchantId: kotlin.String, transactionType: kotlin.Any?, endDate: kotlin.Any?, startDate: kotlin.Any?, limit: java.math.BigDecimal?, offset: java.math.BigDecimal?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (transactionType != null) {
                    put("transactionType", listOf(transactionType.toString()))
                }
                if (endDate != null) {
                    put("endDate", listOf(endDate.toString()))
                }
                if (startDate != null) {
                    put("startDate", listOf(startDate.toString()))
                }
                put("merchantId", listOf(merchantId.toString()))
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/canary/balance/history",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/canary/balance
     * Get Merchant Balance
     * Retrieves the merchant&#39;s own master balance (their earnings) available for payouts.
     * @return MerchantBalanceResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getMerchantBalance() : MerchantBalanceResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = getMerchantBalanceWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MerchantBalanceResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/canary/balance
     * Get Merchant Balance
     * Retrieves the merchant&#39;s own master balance (their earnings) available for payouts.
     * @return ApiResponse<MerchantBalanceResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getMerchantBalanceWithHttpInfo() : ApiResponse<MerchantBalanceResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getMerchantBalanceRequestConfig()

        return@withContext request<Unit, MerchantBalanceResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMerchantBalance
     *
     * @return RequestConfig
     */
    fun getMerchantBalanceRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/canary/balance",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
