/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.cashful.kotlin.sdk.model.CheckoutSessionResponseDto
import com.cashful.kotlin.sdk.model.CreateCheckoutSessionDto
import com.cashful.kotlin.sdk.model.ErrorResponseDto
import com.cashful.kotlin.sdk.model.ListCheckoutSessionsResponseDto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.cashful.kotlin.sdk.infrastructure.ApiClient
import com.cashful.kotlin.sdk.infrastructure.ApiResponse
import com.cashful.kotlin.sdk.infrastructure.ClientException
import com.cashful.kotlin.sdk.infrastructure.ClientError
import com.cashful.kotlin.sdk.infrastructure.ServerException
import com.cashful.kotlin.sdk.infrastructure.ServerError
import com.cashful.kotlin.sdk.infrastructure.MultiValueMap
import com.cashful.kotlin.sdk.infrastructure.PartConfig
import com.cashful.kotlin.sdk.infrastructure.RequestConfig
import com.cashful.kotlin.sdk.infrastructure.RequestMethod
import com.cashful.kotlin.sdk.infrastructure.ResponseType
import com.cashful.kotlin.sdk.infrastructure.Success
import com.cashful.kotlin.sdk.infrastructure.toMultiValue

class CheckoutsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:3000")
        }
    }

    /**
     * POST /api/canary/checkout/sessions
     * Create Hosted Checkout
     * Creates a hosted payment page. Used for: (1) A standard e-commerce purchase, or (2) a \&quot;Pay-In\&quot; to fund a CustomerBalance.
     * @param createCheckoutSessionDto Checkout session details
     * @return CheckoutSessionResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createCheckoutSession(createCheckoutSessionDto: CreateCheckoutSessionDto) : CheckoutSessionResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = createCheckoutSessionWithHttpInfo(createCheckoutSessionDto = createCheckoutSessionDto)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CheckoutSessionResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/canary/checkout/sessions
     * Create Hosted Checkout
     * Creates a hosted payment page. Used for: (1) A standard e-commerce purchase, or (2) a \&quot;Pay-In\&quot; to fund a CustomerBalance.
     * @param createCheckoutSessionDto Checkout session details
     * @return ApiResponse<CheckoutSessionResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createCheckoutSessionWithHttpInfo(createCheckoutSessionDto: CreateCheckoutSessionDto) : ApiResponse<CheckoutSessionResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createCheckoutSessionRequestConfig(createCheckoutSessionDto = createCheckoutSessionDto)

        return@withContext request<CreateCheckoutSessionDto, CheckoutSessionResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createCheckoutSession
     *
     * @param createCheckoutSessionDto Checkout session details
     * @return RequestConfig
     */
    fun createCheckoutSessionRequestConfig(createCheckoutSessionDto: CreateCheckoutSessionDto) : RequestConfig<CreateCheckoutSessionDto> {
        val localVariableBody = createCheckoutSessionDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/canary/checkout/sessions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/canary/checkout/sessions
     * List Checkout Sessions
     * Lists checkout sessions
     * @param total Total number of items available
     * @param hasMore Whether there are more items available beyond this response
     * @param merchantId The ID of the merchant. This parameter is required.
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @param status The status to filter checkout sessions (optional)
     * @return ListCheckoutSessionsResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listCheckoutSessions(total: java.math.BigDecimal, hasMore: kotlin.Boolean, merchantId: kotlin.String, limit: java.math.BigDecimal? = null, offset: java.math.BigDecimal? = null, status: kotlin.String? = null) : ListCheckoutSessionsResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = listCheckoutSessionsWithHttpInfo(total = total, hasMore = hasMore, merchantId = merchantId, limit = limit, offset = offset, status = status)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ListCheckoutSessionsResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/canary/checkout/sessions
     * List Checkout Sessions
     * Lists checkout sessions
     * @param total Total number of items available
     * @param hasMore Whether there are more items available beyond this response
     * @param merchantId The ID of the merchant. This parameter is required.
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @param status The status to filter checkout sessions (optional)
     * @return ApiResponse<ListCheckoutSessionsResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listCheckoutSessionsWithHttpInfo(total: java.math.BigDecimal, hasMore: kotlin.Boolean, merchantId: kotlin.String, limit: java.math.BigDecimal?, offset: java.math.BigDecimal?, status: kotlin.String?) : ApiResponse<ListCheckoutSessionsResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listCheckoutSessionsRequestConfig(total = total, hasMore = hasMore, merchantId = merchantId, limit = limit, offset = offset, status = status)

        return@withContext request<Unit, ListCheckoutSessionsResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listCheckoutSessions
     *
     * @param total Total number of items available
     * @param hasMore Whether there are more items available beyond this response
     * @param merchantId The ID of the merchant. This parameter is required.
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @param status The status to filter checkout sessions (optional)
     * @return RequestConfig
     */
    fun listCheckoutSessionsRequestConfig(total: java.math.BigDecimal, hasMore: kotlin.Boolean, merchantId: kotlin.String, limit: java.math.BigDecimal?, offset: java.math.BigDecimal?, status: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
                put("total", listOf(total.toString()))
                put("hasMore", listOf(hasMore.toString()))
                put("merchantId", listOf(merchantId.toString()))
                if (status != null) {
                    put("status", listOf(status.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/canary/checkout/sessions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/canary/checkout/sessions/{id}
     * Retrieve Checkout Session
     * Retrieves details of a specific checkout session
     * @param id The unique identifier of the checkout session
     * @return CheckoutSessionResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun retrieveCheckoutSession(id: kotlin.String) : CheckoutSessionResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = retrieveCheckoutSessionWithHttpInfo(id = id)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CheckoutSessionResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/canary/checkout/sessions/{id}
     * Retrieve Checkout Session
     * Retrieves details of a specific checkout session
     * @param id The unique identifier of the checkout session
     * @return ApiResponse<CheckoutSessionResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun retrieveCheckoutSessionWithHttpInfo(id: kotlin.String) : ApiResponse<CheckoutSessionResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = retrieveCheckoutSessionRequestConfig(id = id)

        return@withContext request<Unit, CheckoutSessionResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation retrieveCheckoutSession
     *
     * @param id The unique identifier of the checkout session
     * @return RequestConfig
     */
    fun retrieveCheckoutSessionRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/canary/checkout/sessions/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
