/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.cashful.kotlin.sdk.model.CreateProductDto
import com.cashful.kotlin.sdk.model.ErrorResponseDto
import com.cashful.kotlin.sdk.model.ListProductsResponseDto
import com.cashful.kotlin.sdk.model.ProductResponseDto
import com.cashful.kotlin.sdk.model.UpdateProductDto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.cashful.kotlin.sdk.infrastructure.ApiClient
import com.cashful.kotlin.sdk.infrastructure.ApiResponse
import com.cashful.kotlin.sdk.infrastructure.ClientException
import com.cashful.kotlin.sdk.infrastructure.ClientError
import com.cashful.kotlin.sdk.infrastructure.ServerException
import com.cashful.kotlin.sdk.infrastructure.ServerError
import com.cashful.kotlin.sdk.infrastructure.MultiValueMap
import com.cashful.kotlin.sdk.infrastructure.PartConfig
import com.cashful.kotlin.sdk.infrastructure.RequestConfig
import com.cashful.kotlin.sdk.infrastructure.RequestMethod
import com.cashful.kotlin.sdk.infrastructure.ResponseType
import com.cashful.kotlin.sdk.infrastructure.Success
import com.cashful.kotlin.sdk.infrastructure.toMultiValue

class ProductsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:9000")
        }
    }

    /**
     * POST /api/canary/products
     * Create Product
     * Defines a product in the merchant&#39;s catalog (e.g., \&quot;Airtime,\&quot; \&quot;Data\&quot;).
     * @param createProductDto Product details
     * @return ProductResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createProduct(createProductDto: CreateProductDto) : ProductResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = createProductWithHttpInfo(createProductDto = createProductDto)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ProductResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/canary/products
     * Create Product
     * Defines a product in the merchant&#39;s catalog (e.g., \&quot;Airtime,\&quot; \&quot;Data\&quot;).
     * @param createProductDto Product details
     * @return ApiResponse<ProductResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createProductWithHttpInfo(createProductDto: CreateProductDto) : ApiResponse<ProductResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createProductRequestConfig(createProductDto = createProductDto)

        return@withContext request<CreateProductDto, ProductResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createProduct
     *
     * @param createProductDto Product details
     * @return RequestConfig
     */
    fun createProductRequestConfig(createProductDto: CreateProductDto) : RequestConfig<CreateProductDto> {
        val localVariableBody = createProductDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/canary/products",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/canary/products
     * List Products
     * Retrieves all products in the merchant&#39;s catalog.
     * @param merchantId The ID of the merchant. This parameter is required.
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @param active Filter by active status (optional)
     * @return ListProductsResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listProducts(merchantId: kotlin.String, limit: java.math.BigDecimal? = null, offset: java.math.BigDecimal? = null, active: kotlin.Boolean? = null) : ListProductsResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = listProductsWithHttpInfo(merchantId = merchantId, limit = limit, offset = offset, active = active)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ListProductsResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/canary/products
     * List Products
     * Retrieves all products in the merchant&#39;s catalog.
     * @param merchantId The ID of the merchant. This parameter is required.
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @param active Filter by active status (optional)
     * @return ApiResponse<ListProductsResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listProductsWithHttpInfo(merchantId: kotlin.String, limit: java.math.BigDecimal?, offset: java.math.BigDecimal?, active: kotlin.Boolean?) : ApiResponse<ListProductsResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listProductsRequestConfig(merchantId = merchantId, limit = limit, offset = offset, active = active)

        return@withContext request<Unit, ListProductsResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listProducts
     *
     * @param merchantId The ID of the merchant. This parameter is required.
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @param active Filter by active status (optional)
     * @return RequestConfig
     */
    fun listProductsRequestConfig(merchantId: kotlin.String, limit: java.math.BigDecimal?, offset: java.math.BigDecimal?, active: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
                put("merchantId", listOf(merchantId.toString()))
                if (active != null) {
                    put("active", listOf(active.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/canary/products",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/canary/products/{id}
     * Update Product
     * Updates a product&#39;s name, description, or metadata.
     * @param id The unique identifier of the product
     * @param updateProductDto Product update details
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateProduct(id: kotlin.String, updateProductDto: UpdateProductDto) : kotlin.Any = withContext(Dispatchers.IO) {
        val localVarResponse = updateProductWithHttpInfo(id = id, updateProductDto = updateProductDto)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/canary/products/{id}
     * Update Product
     * Updates a product&#39;s name, description, or metadata.
     * @param id The unique identifier of the product
     * @param updateProductDto Product update details
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateProductWithHttpInfo(id: kotlin.String, updateProductDto: UpdateProductDto) : ApiResponse<kotlin.Any?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateProductRequestConfig(id = id, updateProductDto = updateProductDto)

        return@withContext request<UpdateProductDto, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateProduct
     *
     * @param id The unique identifier of the product
     * @param updateProductDto Product update details
     * @return RequestConfig
     */
    fun updateProductRequestConfig(id: kotlin.String, updateProductDto: UpdateProductDto) : RequestConfig<UpdateProductDto> {
        val localVariableBody = updateProductDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/canary/products/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
