/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.api.AuthenticationApi
import com.cashful.kotlin.sdk.model.AcceptInvitationDto
import com.cashful.kotlin.sdk.model.CancelInvitationDto
import com.cashful.kotlin.sdk.model.CreateApiKeyDto
import com.cashful.kotlin.sdk.model.CreateOrganizationDto
import com.cashful.kotlin.sdk.model.DeleteApiKeyDto
import com.cashful.kotlin.sdk.model.DeleteOrganizationDto
import com.cashful.kotlin.sdk.model.ErrorResponseDto
import com.cashful.kotlin.sdk.model.ForgotPasswordDto
import com.cashful.kotlin.sdk.model.GetSessionResponseDto
import com.cashful.kotlin.sdk.model.InviteMemberDto
import com.cashful.kotlin.sdk.model.RejectInvitationDto
import com.cashful.kotlin.sdk.model.RemoveMemberDto
import com.cashful.kotlin.sdk.model.ResetPasswordDto
import com.cashful.kotlin.sdk.model.SetActiveOrganizationDto
import com.cashful.kotlin.sdk.model.SignInDto
import com.cashful.kotlin.sdk.model.SignUpDto
import com.cashful.kotlin.sdk.model.UpdateApiKeyDto
import com.cashful.kotlin.sdk.model.UpdateMemberRoleDto
import com.cashful.kotlin.sdk.model.UpdateOrganizationDto
import com.cashful.kotlin.sdk.model.VerifyApiKeyDto

class AuthenticationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthenticationApi
        //val apiInstance = AuthenticationApi()

        // to test acceptInvitation
        should("test acceptInvitation") {
            // uncomment below to test acceptInvitation
            //val acceptInvitationDto : AcceptInvitationDto =  // AcceptInvitationDto | 
            //apiInstance.acceptInvitation(acceptInvitationDto)
        }

        // to test cancelInvitation
        should("test cancelInvitation") {
            // uncomment below to test cancelInvitation
            //val cancelInvitationDto : CancelInvitationDto =  // CancelInvitationDto | 
            //apiInstance.cancelInvitation(cancelInvitationDto)
        }

        // to test createApiKey
        should("test createApiKey") {
            // uncomment below to test createApiKey
            //val createApiKeyDto : CreateApiKeyDto =  // CreateApiKeyDto | 
            //apiInstance.createApiKey(createApiKeyDto)
        }

        // to test createOrganization
        should("test createOrganization") {
            // uncomment below to test createOrganization
            //val createOrganizationDto : CreateOrganizationDto =  // CreateOrganizationDto | 
            //apiInstance.createOrganization(createOrganizationDto)
        }

        // to test deleteApiKey
        should("test deleteApiKey") {
            // uncomment below to test deleteApiKey
            //val deleteApiKeyDto : DeleteApiKeyDto =  // DeleteApiKeyDto | 
            //apiInstance.deleteApiKey(deleteApiKeyDto)
        }

        // to test deleteOrganization
        should("test deleteOrganization") {
            // uncomment below to test deleteOrganization
            //val deleteOrganizationDto : DeleteOrganizationDto =  // DeleteOrganizationDto | 
            //apiInstance.deleteOrganization(deleteOrganizationDto)
        }

        // to test forgetPassword
        should("test forgetPassword") {
            // uncomment below to test forgetPassword
            //val forgotPasswordDto : ForgotPasswordDto =  // ForgotPasswordDto | 
            //apiInstance.forgetPassword(forgotPasswordDto)
        }

        // to test getSession
        should("test getSession") {
            // uncomment below to test getSession
            //val result : GetSessionResponseDto = apiInstance.getSession()
            //result shouldBe ("TODO")
        }

        // to test inviteMember
        should("test inviteMember") {
            // uncomment below to test inviteMember
            //val inviteMemberDto : InviteMemberDto =  // InviteMemberDto | 
            //apiInstance.inviteMember(inviteMemberDto)
        }

        // to test listApiKeys
        should("test listApiKeys") {
            // uncomment below to test listApiKeys
            //apiInstance.listApiKeys()
        }

        // to test listOrganizations
        should("test listOrganizations") {
            // uncomment below to test listOrganizations
            //apiInstance.listOrganizations()
        }

        // to test rejectInvitation
        should("test rejectInvitation") {
            // uncomment below to test rejectInvitation
            //val rejectInvitationDto : RejectInvitationDto =  // RejectInvitationDto | 
            //apiInstance.rejectInvitation(rejectInvitationDto)
        }

        // to test removeMember
        should("test removeMember") {
            // uncomment below to test removeMember
            //val removeMemberDto : RemoveMemberDto =  // RemoveMemberDto | 
            //apiInstance.removeMember(removeMemberDto)
        }

        // to test resetPassword
        should("test resetPassword") {
            // uncomment below to test resetPassword
            //val resetPasswordDto : ResetPasswordDto =  // ResetPasswordDto | 
            //apiInstance.resetPassword(resetPasswordDto)
        }

        // to test setActiveOrganization
        should("test setActiveOrganization") {
            // uncomment below to test setActiveOrganization
            //val setActiveOrganizationDto : SetActiveOrganizationDto =  // SetActiveOrganizationDto | 
            //apiInstance.setActiveOrganization(setActiveOrganizationDto)
        }

        // to test signInEmail
        should("test signInEmail") {
            // uncomment below to test signInEmail
            //val signInDto : SignInDto =  // SignInDto | 
            //apiInstance.signInEmail(signInDto)
        }

        // to test signOut
        should("test signOut") {
            // uncomment below to test signOut
            //apiInstance.signOut()
        }

        // to test signUpEmail
        should("test signUpEmail") {
            // uncomment below to test signUpEmail
            //val signUpDto : SignUpDto =  // SignUpDto | 
            //apiInstance.signUpEmail(signUpDto)
        }

        // to test updateApiKey
        should("test updateApiKey") {
            // uncomment below to test updateApiKey
            //val updateApiKeyDto : UpdateApiKeyDto =  // UpdateApiKeyDto | 
            //apiInstance.updateApiKey(updateApiKeyDto)
        }

        // to test updateMemberRole
        should("test updateMemberRole") {
            // uncomment below to test updateMemberRole
            //val updateMemberRoleDto : UpdateMemberRoleDto =  // UpdateMemberRoleDto | 
            //apiInstance.updateMemberRole(updateMemberRoleDto)
        }

        // to test updateOrganization
        should("test updateOrganization") {
            // uncomment below to test updateOrganization
            //val updateOrganizationDto : UpdateOrganizationDto =  // UpdateOrganizationDto | 
            //apiInstance.updateOrganization(updateOrganizationDto)
        }

        // to test verifyApiKey
        should("test verifyApiKey") {
            // uncomment below to test verifyApiKey
            //val verifyApiKeyDto : VerifyApiKeyDto =  // VerifyApiKeyDto | 
            //apiInstance.verifyApiKey(verifyApiKeyDto)
        }

    }
}
