/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.api.BalanceApi
import com.cashful.kotlin.sdk.model.BalanceHistoryResponseDto
import com.cashful.kotlin.sdk.model.ErrorResponseDto
import com.cashful.kotlin.sdk.model.MerchantBalanceResponseDto

class BalanceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BalanceApi
        //val apiInstance = BalanceApi()

        // to test getBalanceHistory
        should("test getBalanceHistory") {
            // uncomment below to test getBalanceHistory
            //val merchantId : kotlin.String = merchantId_example // kotlin.String | The ID of the merchant. This parameter is required.
            //val transactionType : kotlin.Any =  // kotlin.Any | Filter by transaction type (e.g., \"credit\", \"debit\", \"fee\", \"payout\")
            //val endDate : kotlin.Any =  // kotlin.Any | Filter transactions until this date (ISO 8601 format)
            //val startDate : kotlin.Any =  // kotlin.Any | Filter transactions from this date (ISO 8601 format)
            //val limit : java.math.BigDecimal = 8.14 // java.math.BigDecimal | Maximum number of records to return
            //val offset : java.math.BigDecimal = 8.14 // java.math.BigDecimal | Number of records to skip
            //val result : BalanceHistoryResponseDto = apiInstance.getBalanceHistory(merchantId, transactionType, endDate, startDate, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test getMerchantBalance
        should("test getMerchantBalance") {
            // uncomment below to test getMerchantBalance
            //val result : MerchantBalanceResponseDto = apiInstance.getMerchantBalance()
            //result shouldBe ("TODO")
        }

    }
}
