/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.api.CheckoutsApi
import com.cashful.kotlin.sdk.model.CheckoutSessionResponseDto
import com.cashful.kotlin.sdk.model.CreateCheckoutSessionDto
import com.cashful.kotlin.sdk.model.ErrorResponseDto

class CheckoutsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutsApi
        //val apiInstance = CheckoutsApi()

        // to test createCheckoutSession
        should("test createCheckoutSession") {
            // uncomment below to test createCheckoutSession
            //val createCheckoutSessionDto : CreateCheckoutSessionDto =  // CreateCheckoutSessionDto | Checkout session details
            //val result : CheckoutSessionResponseDto = apiInstance.createCheckoutSession(createCheckoutSessionDto)
            //result shouldBe ("TODO")
        }

    }
}
