/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.api.KYCApi
import com.cashful.kotlin.sdk.model.CreateOrganizationKycDto
import com.cashful.kotlin.sdk.model.ErrorResponseDto
import com.cashful.kotlin.sdk.model.OrganizationKycResponseDto
import com.cashful.kotlin.sdk.model.UpdateOrganizationKycDto

class KYCApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of KYCApi
        //val apiInstance = KYCApi()

        // to test createKyc
        should("test createKyc") {
            // uncomment below to test createKyc
            //val createOrganizationKycDto : CreateOrganizationKycDto =  // CreateOrganizationKycDto | 
            //val result : OrganizationKycResponseDto = apiInstance.createKyc(createOrganizationKycDto)
            //result shouldBe ("TODO")
        }

        // to test getKyc
        should("test getKyc") {
            // uncomment below to test getKyc
            //val organizationId : kotlin.String = organizationId_example // kotlin.String | 
            //val result : OrganizationKycResponseDto = apiInstance.getKyc(organizationId)
            //result shouldBe ("TODO")
        }

        // to test updateKyc
        should("test updateKyc") {
            // uncomment below to test updateKyc
            //val id : kotlin.String = id_example // kotlin.String | 
            //val updateOrganizationKycDto : UpdateOrganizationKycDto =  // UpdateOrganizationKycDto | 
            //apiInstance.updateKyc(id, updateOrganizationKycDto)
        }

    }
}
