/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.api.PaymentIntentsApi
import com.cashful.kotlin.sdk.model.CreatePaymentIntentDto
import com.cashful.kotlin.sdk.model.ErrorResponseDto
import com.cashful.kotlin.sdk.model.PaymentIntentResponseDto

class PaymentIntentsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentIntentsApi
        //val apiInstance = PaymentIntentsApi()

        // to test createPaymentIntent
        should("test createPaymentIntent") {
            // uncomment below to test createPaymentIntent
            //val createPaymentIntentDto : CreatePaymentIntentDto =  // CreatePaymentIntentDto | Payment intent details
            //val result : PaymentIntentResponseDto = apiInstance.createPaymentIntent(createPaymentIntentDto)
            //result shouldBe ("TODO")
        }

        // to test retrievePaymentIntent
        should("test retrievePaymentIntent") {
            // uncomment below to test retrievePaymentIntent
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the payment intent
            //val result : kotlin.Any = apiInstance.retrievePaymentIntent(id)
            //result shouldBe ("TODO")
        }

    }
}
