/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.api.PaymentMethodsApi
import com.cashful.kotlin.sdk.model.ErrorResponseDto
import com.cashful.kotlin.sdk.model.PaymentMethodResponseDto

class PaymentMethodsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentMethodsApi
        //val apiInstance = PaymentMethodsApi()

        // to test deletePaymentMethod
        should("test deletePaymentMethod") {
            // uncomment below to test deletePaymentMethod
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the payment method
            //val result : kotlin.Any = apiInstance.deletePaymentMethod(id)
            //result shouldBe ("TODO")
        }

        // to test retrievePaymentMethod
        should("test retrievePaymentMethod") {
            // uncomment below to test retrievePaymentMethod
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the payment method
            //val result : PaymentMethodResponseDto = apiInstance.retrievePaymentMethod(id)
            //result shouldBe ("TODO")
        }

    }
}
