/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.api.PayoutsApi
import com.cashful.kotlin.sdk.model.CreatePayoutDto
import com.cashful.kotlin.sdk.model.ErrorResponseDto
import com.cashful.kotlin.sdk.model.ListPayoutsResponseDto
import com.cashful.kotlin.sdk.model.PayoutResponseDto

class PayoutsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayoutsApi
        //val apiInstance = PayoutsApi()

        // to test createPayout
        should("test createPayout") {
            // uncomment below to test createPayout
            //val createPayoutDto : CreatePayoutDto =  // CreatePayoutDto | Payout details
            //val result : PayoutResponseDto = apiInstance.createPayout(createPayoutDto)
            //result shouldBe ("TODO")
        }

        // to test listPayouts
        should("test listPayouts") {
            // uncomment below to test listPayouts
            //val merchantId : kotlin.String = merchantId_example // kotlin.String | The ID of the merchant. This parameter is required.
            //val status : kotlin.Any =  // kotlin.Any | Filter by status
            //val limit : java.math.BigDecimal = 8.14 // java.math.BigDecimal | Maximum number of records to return
            //val offset : java.math.BigDecimal = 8.14 // java.math.BigDecimal | Number of records to skip
            //val result : ListPayoutsResponseDto = apiInstance.listPayouts(merchantId, status, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
