/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.api.ProductsApi
import com.cashful.kotlin.sdk.model.CreateProductDto
import com.cashful.kotlin.sdk.model.ErrorResponseDto
import com.cashful.kotlin.sdk.model.ListProductsResponseDto
import com.cashful.kotlin.sdk.model.ProductResponseDto
import com.cashful.kotlin.sdk.model.UpdateProductDto

class ProductsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductsApi
        //val apiInstance = ProductsApi()

        // to test createProduct
        should("test createProduct") {
            // uncomment below to test createProduct
            //val createProductDto : CreateProductDto =  // CreateProductDto | Product details
            //val result : ProductResponseDto = apiInstance.createProduct(createProductDto)
            //result shouldBe ("TODO")
        }

        // to test listProducts
        should("test listProducts") {
            // uncomment below to test listProducts
            //val merchantId : kotlin.String = merchantId_example // kotlin.String | The ID of the merchant. This parameter is required.
            //val active : kotlin.Boolean = true // kotlin.Boolean | Filter by active status
            //val limit : java.math.BigDecimal = 8.14 // java.math.BigDecimal | Maximum number of records to return
            //val offset : java.math.BigDecimal = 8.14 // java.math.BigDecimal | Number of records to skip
            //val result : ListProductsResponseDto = apiInstance.listProducts(merchantId, active, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test updateProduct
        should("test updateProduct") {
            // uncomment below to test updateProduct
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the product
            //val updateProductDto : UpdateProductDto =  // UpdateProductDto | Product update details
            //val result : kotlin.Any = apiInstance.updateProduct(id, updateProductDto)
            //result shouldBe ("TODO")
        }

    }
}
