/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.api.AnalyticsApi
import com.cashful.model.AnalyticsResponseDto
import com.cashful.model.AnalyticsSummaryDto
import com.cashful.model.BadRequestResponseDto
import com.cashful.model.InternalServerErrorResponseDto
import com.cashful.model.UnauthorizedResponseDto

class AnalyticsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AnalyticsApi
        //val apiInstance = AnalyticsApi()

        // to test getAnalytics
        should("test getAnalytics") {
            // uncomment below to test getAnalytics
            //val merchantId : kotlin.String = merchant_123 // kotlin.String | The unique identifier of the merchant. If not provided, defaults to the authenticated user's active organization.
            //val result : AnalyticsResponseDto = apiInstance.getAnalytics(merchantId)
            //result shouldBe ("TODO")
        }

        // to test getAnalyticsSummary
        should("test getAnalyticsSummary") {
            // uncomment below to test getAnalyticsSummary
            //val merchantId : kotlin.String = merchant_123 // kotlin.String | The unique identifier of the merchant. If not provided, defaults to the authenticated user's active organization.
            //val result : AnalyticsSummaryDto = apiInstance.getAnalyticsSummary(merchantId)
            //result shouldBe ("TODO")
        }

    }
}
