/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.api.CheckoutsApi
import com.cashful.model.CheckoutSessionResponseDto
import com.cashful.model.CreateCheckoutSessionDto
import com.cashful.model.ErrorResponseDto
import com.cashful.model.ListCheckoutSessionsResponseDto

class CheckoutsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutsApi
        //val apiInstance = CheckoutsApi()

        // to test createCheckoutSession
        should("test createCheckoutSession") {
            // uncomment below to test createCheckoutSession
            //val createCheckoutSessionDto : CreateCheckoutSessionDto =  // CreateCheckoutSessionDto | Checkout session details
            //val result : CheckoutSessionResponseDto = apiInstance.createCheckoutSession(createCheckoutSessionDto)
            //result shouldBe ("TODO")
        }

        // to test listCheckoutSessions
        should("test listCheckoutSessions") {
            // uncomment below to test listCheckoutSessions
            //val merchantId : kotlin.String = merchantId_example // kotlin.String | The ID of the merchant to filter checkout sessions
            //val limit : java.math.BigDecimal = 50 // java.math.BigDecimal | Maximum number of records to return
            //val offset : java.math.BigDecimal = 0 // java.math.BigDecimal | Number of records to skip
            //val status : kotlin.String = status_example // kotlin.String | The status to filter checkout sessions
            //val result : ListCheckoutSessionsResponseDto = apiInstance.listCheckoutSessions(merchantId, limit, offset, status)
            //result shouldBe ("TODO")
        }

        // to test retrieveCheckoutSession
        should("test retrieveCheckoutSession") {
            // uncomment below to test retrieveCheckoutSession
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the checkout session
            //val result : CheckoutSessionResponseDto = apiInstance.retrieveCheckoutSession(id)
            //result shouldBe ("TODO")
        }

    }
}
