/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.api.NotificationsApi
import com.cashful.model.NotificationDto
import com.cashful.model.SendEmail200Response
import com.cashful.model.SendEmailDto
import com.cashful.model.SendMultiChannelNotification200Response
import com.cashful.model.SendSms200Response
import com.cashful.model.SendSmsDto

class NotificationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationsApi
        //val apiInstance = NotificationsApi()

        // to test sendEmail
        should("test sendEmail") {
            // uncomment below to test sendEmail
            //val sendEmailDto : SendEmailDto =  // SendEmailDto | 
            //val result : SendEmail200Response = apiInstance.sendEmail(sendEmailDto)
            //result shouldBe ("TODO")
        }

        // to test sendMultiChannelNotification
        should("test sendMultiChannelNotification") {
            // uncomment below to test sendMultiChannelNotification
            //val result : SendMultiChannelNotification200Response = apiInstance.sendMultiChannelNotification()
            //result shouldBe ("TODO")
        }

        // to test sendNotification
        should("test sendNotification") {
            // uncomment below to test sendNotification
            //val notificationDto : NotificationDto =  // NotificationDto | 
            //apiInstance.sendNotification(notificationDto)
        }

        // to test sendSms
        should("test sendSms") {
            // uncomment below to test sendSms
            //val sendSmsDto : SendSmsDto =  // SendSmsDto | 
            //val result : SendSms200Response = apiInstance.sendSms(sendSmsDto)
            //result shouldBe ("TODO")
        }

    }
}
