/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.api.PaymentIntentsApi
import com.cashful.model.BadRequestResponseDto
import com.cashful.model.ConfirmPaymentIntentDto
import com.cashful.model.ConfirmPaymentIntentResponseDto
import com.cashful.model.CreatePaymentIntentDto
import com.cashful.model.InternalServerErrorResponseDto
import com.cashful.model.ListPaymentIntentsResponseDto
import com.cashful.model.NotFoundResponseDto
import com.cashful.model.PaymentIntentResponseDto
import com.cashful.model.UnauthorizedResponseDto

class PaymentIntentsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentIntentsApi
        //val apiInstance = PaymentIntentsApi()

        // to test cancelPaymentIntent
        should("test cancelPaymentIntent") {
            // uncomment below to test cancelPaymentIntent
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the payment intent
            //val result : PaymentIntentResponseDto = apiInstance.cancelPaymentIntent(id)
            //result shouldBe ("TODO")
        }

        // to test confirmPaymentIntent
        should("test confirmPaymentIntent") {
            // uncomment below to test confirmPaymentIntent
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the payment intent
            //val confirmPaymentIntentDto : ConfirmPaymentIntentDto =  // ConfirmPaymentIntentDto | 
            //val result : ConfirmPaymentIntentResponseDto = apiInstance.confirmPaymentIntent(id, confirmPaymentIntentDto)
            //result shouldBe ("TODO")
        }

        // to test createPaymentIntent
        should("test createPaymentIntent") {
            // uncomment below to test createPaymentIntent
            //val createPaymentIntentDto : CreatePaymentIntentDto =  // CreatePaymentIntentDto | Payment intent details
            //val result : PaymentIntentResponseDto = apiInstance.createPaymentIntent(createPaymentIntentDto)
            //result shouldBe ("TODO")
        }

        // to test listPaymentIntents
        should("test listPaymentIntents") {
            // uncomment below to test listPaymentIntents
            //val status : kotlin.String = status_example // kotlin.String | 
            //val offset : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val limit : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val merchantId : kotlin.String = merchantId_example // kotlin.String | 
            //val result : ListPaymentIntentsResponseDto = apiInstance.listPaymentIntents(status, offset, limit, merchantId)
            //result shouldBe ("TODO")
        }

        // to test retrievePaymentIntent
        should("test retrievePaymentIntent") {
            // uncomment below to test retrievePaymentIntent
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the payment intent
            //val result : PaymentIntentResponseDto = apiInstance.retrievePaymentIntent(id)
            //result shouldBe ("TODO")
        }

    }
}
