/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.api.PaymentLinksApi
import com.cashful.model.BadRequestResponseDto
import com.cashful.model.CreatePaymentLinkDto
import com.cashful.model.InternalServerErrorResponseDto
import com.cashful.model.ListPaymentLinksResponseDto
import com.cashful.model.NotFoundResponseDto
import com.cashful.model.PaymentLinkResponseDto
import com.cashful.model.UnauthorizedResponseDto
import com.cashful.model.UpdatePaymentLinkDto

class PaymentLinksApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentLinksApi
        //val apiInstance = PaymentLinksApi()

        // to test createPaymentLink
        should("test createPaymentLink") {
            // uncomment below to test createPaymentLink
            //val createPaymentLinkDto : CreatePaymentLinkDto =  // CreatePaymentLinkDto | Payment link details
            //val result : PaymentLinkResponseDto = apiInstance.createPaymentLink(createPaymentLinkDto)
            //result shouldBe ("TODO")
        }

        // to test listPaymentLinks
        should("test listPaymentLinks") {
            // uncomment below to test listPaymentLinks
            //val limit : java.math.BigDecimal = 50 // java.math.BigDecimal | Maximum number of items to return
            //val offset : java.math.BigDecimal = 0 // java.math.BigDecimal | Number of items to skip
            //val filter : kotlin.String = {"ids":["prod_123","prod_456"]} // kotlin.String | JSON string used for dynamic filtering
            //val sort : kotlin.String = createdAt // kotlin.String | Field name to sort by
            //val order : kotlin.String = DESC // kotlin.String | Sort direction
            //val merchantId : kotlin.String = merchantId_example // kotlin.String | The ID of the merchant whose payment links are being requested. If omitted, defaults to the authenticated merchant.
            //val active : kotlin.Boolean = true // kotlin.Boolean | Filter by active status
            //val result : ListPaymentLinksResponseDto = apiInstance.listPaymentLinks(limit, offset, filter, sort, order, merchantId, active)
            //result shouldBe ("TODO")
        }

        // to test retrievePaymentLink
        should("test retrievePaymentLink") {
            // uncomment below to test retrievePaymentLink
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the payment link
            //val result : PaymentLinkResponseDto = apiInstance.retrievePaymentLink(id)
            //result shouldBe ("TODO")
        }

        // to test updatePaymentLink
        should("test updatePaymentLink") {
            // uncomment below to test updatePaymentLink
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the payment link
            //val updatePaymentLinkDto : UpdatePaymentLinkDto =  // UpdatePaymentLinkDto | Payment link update details
            //val result : kotlin.Any = apiInstance.updatePaymentLink(id, updatePaymentLinkDto)
            //result shouldBe ("TODO")
        }

    }
}
