/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.api.ProductsApi
import com.cashful.model.BadRequestResponseDto
import com.cashful.model.BulkIdsDto
import com.cashful.model.BulkUpdateProductsInputDto
import com.cashful.model.CreateProductDto
import com.cashful.model.InternalServerErrorResponseDto
import com.cashful.model.ListProductsResponseDto
import com.cashful.model.NotFoundResponseDto
import com.cashful.model.ProductResponseDto
import com.cashful.model.UnauthorizedResponseDto
import com.cashful.model.UpdateProductDto

class ProductsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductsApi
        //val apiInstance = ProductsApi()

        // to test createProduct
        should("test createProduct") {
            // uncomment below to test createProduct
            //val createProductDto : CreateProductDto =  // CreateProductDto | Product details
            //val result : ProductResponseDto = apiInstance.createProduct(createProductDto)
            //result shouldBe ("TODO")
        }

        // to test deleteProduct
        should("test deleteProduct") {
            // uncomment below to test deleteProduct
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the product
            //val result : ProductResponseDto = apiInstance.deleteProduct(id)
            //result shouldBe ("TODO")
        }

        // to test deleteProductsBulk
        should("test deleteProductsBulk") {
            // uncomment below to test deleteProductsBulk
            //val bulkIdsDto : BulkIdsDto =  // BulkIdsDto | 
            //val result : kotlin.Any = apiInstance.deleteProductsBulk(bulkIdsDto)
            //result shouldBe ("TODO")
        }

        // to test listProducts
        should("test listProducts") {
            // uncomment below to test listProducts
            //val limit : java.math.BigDecimal = 50 // java.math.BigDecimal | Maximum number of items to return
            //val offset : java.math.BigDecimal = 0 // java.math.BigDecimal | Number of items to skip
            //val filter : kotlin.String = {"ids":["prod_123","prod_456"]} // kotlin.String | JSON string used for dynamic filtering
            //val sort : kotlin.String = createdAt // kotlin.String | Field name to sort by
            //val order : kotlin.String = DESC // kotlin.String | Sort direction
            //val merchantId : kotlin.String = merchantId_example // kotlin.String | The ID of the merchant whose products are being requested. If not provided, the products of the authenticated merchant will be returned.
            //val active : kotlin.Boolean = true // kotlin.Boolean | Filter by active status
            //val result : ListProductsResponseDto = apiInstance.listProducts(limit, offset, filter, sort, order, merchantId, active)
            //result shouldBe ("TODO")
        }

        // to test retrieveProduct
        should("test retrieveProduct") {
            // uncomment below to test retrieveProduct
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the product
            //val result : ProductResponseDto = apiInstance.retrieveProduct(id)
            //result shouldBe ("TODO")
        }

        // to test updateProduct
        should("test updateProduct") {
            // uncomment below to test updateProduct
            //val id : kotlin.String = id_example // kotlin.String | The unique identifier of the product
            //val updateProductDto : UpdateProductDto =  // UpdateProductDto | Product update details
            //val result : ProductResponseDto = apiInstance.updateProduct(id, updateProductDto)
            //result shouldBe ("TODO")
        }

        // to test updateProductsBulk
        should("test updateProductsBulk") {
            // uncomment below to test updateProductsBulk
            //val bulkUpdateProductsInputDto : BulkUpdateProductsInputDto =  // BulkUpdateProductsInputDto | 
            //val result : kotlin.Any = apiInstance.updateProductsBulk(bulkUpdateProductsInputDto)
            //result shouldBe ("TODO")
        }

    }
}
