/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.api.PurchasesApi
import com.cashful.model.BadRequestResponseDto
import com.cashful.model.CreatePurchaseDto
import com.cashful.model.InternalServerErrorResponseDto
import com.cashful.model.NotFoundResponseDto
import com.cashful.model.PurchaseResponseDto
import com.cashful.model.UnauthorizedResponseDto

class PurchasesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PurchasesApi
        //val apiInstance = PurchasesApi()

        // to test createPurchase
        should("test createPurchase") {
            // uncomment below to test createPurchase
            //val createPurchaseDto : CreatePurchaseDto =  // CreatePurchaseDto | Purchase details
            //val result : PurchaseResponseDto = apiInstance.createPurchase(createPurchaseDto)
            //result shouldBe ("TODO")
        }

    }
}
