/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.api.TransfersApi
import com.cashful.model.CreateTransferDto
import com.cashful.model.ErrorResponseDto
import com.cashful.model.TransferResponseDto

class TransfersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransfersApi
        //val apiInstance = TransfersApi()

        // to test createTransfer
        should("test createTransfer") {
            // uncomment below to test createTransfer
            //val createTransferDto : CreateTransferDto =  // CreateTransferDto | Transfer details
            //val result : TransferResponseDto = apiInstance.createTransfer(createTransferDto)
            //result shouldBe ("TODO")
        }

    }
}
