/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.AdminGetUserResponseDto
import com.cashful.kotlin.sdk.model.SessionUserDto

class AdminGetUserResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdminGetUserResponseDto
        //val modelInstance = AdminGetUserResponseDto()

        // to test the property `user` - User details retrieved successfully
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

    }
}
