/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.AnalyticsResponseDto
import com.cashful.kotlin.sdk.model.CustomerStatsDto
import com.cashful.kotlin.sdk.model.CustomerTransactionDto
import com.cashful.kotlin.sdk.model.TimeframeMetricsDto

class AnalyticsResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AnalyticsResponseDto
        //val modelInstance = AnalyticsResponseDto()

        // to test the property `transactions`
        should("test transactions") {
            // uncomment below to test the property
            //modelInstance.transactions shouldBe ("TODO")
        }

        // to test the property `newCustomers`
        should("test newCustomers") {
            // uncomment below to test the property
            //modelInstance.newCustomers shouldBe ("TODO")
        }

        // to test the property `recentTransactions` - The 5 most recent transactions
        should("test recentTransactions") {
            // uncomment below to test the property
            //modelInstance.recentTransactions shouldBe ("TODO")
        }

    }
}
