/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.ChangePasswordResponseDto
import com.cashful.kotlin.sdk.model.SessionUserDto

class ChangePasswordResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChangePasswordResponseDto
        //val modelInstance = ChangePasswordResponseDto()

        // to test the property `user` - User object
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

        // to test the property `token` - New session token if other sessions were revoked
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

    }
}
