/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.CreateTransferDto

class CreateTransferDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateTransferDto
        //val modelInstance = CreateTransferDto()

        // to test the property `fromCustomerId` - The unique identifier of the customer sending the transfer
        should("test fromCustomerId") {
            // uncomment below to test the property
            //modelInstance.fromCustomerId shouldBe ("TODO")
        }

        // to test the property `toCustomerId` - The unique identifier of the customer receiving the transfer
        should("test toCustomerId") {
            // uncomment below to test the property
            //modelInstance.toCustomerId shouldBe ("TODO")
        }

        // to test the property `amount` - The amount to transfer in the smallest currency unit
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `currency` - The three-letter ISO 4217 currency code
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `merchantId` - The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
        should("test merchantId") {
            // uncomment below to test the property
            //modelInstance.merchantId shouldBe ("TODO")
        }

        // to test the property `description` - Optional description for the transfer
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
