/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.DeleteOrganizationDto

class DeleteOrganizationDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeleteOrganizationDto
        //val modelInstance = DeleteOrganizationDto()

        // to test the property `organizationId` - The ID of the organization to delete
        should("test organizationId") {
            // uncomment below to test the property
            //modelInstance.organizationId shouldBe ("TODO")
        }

    }
}
