/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.DeleteApiKeyDto

class DeleteApiKeyDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeleteApiKeyDto
        //val modelInstance = DeleteApiKeyDto()

        // to test the property `keyId` - The ID of the API key to delete
        should("test keyId") {
            // uncomment below to test the property
            //modelInstance.keyId shouldBe ("TODO")
        }

    }
}
