/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.EventResponseDto

class EventResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EventResponseDto
        //val modelInstance = EventResponseDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `merchantId`
        should("test merchantId") {
            // uncomment below to test the property
            //modelInstance.merchantId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property ``data`` - Event data payload
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `relatedEntityId`
        should("test relatedEntityId") {
            // uncomment below to test the property
            //modelInstance.relatedEntityId shouldBe ("TODO")
        }

        // to test the property `relatedEntityType`
        should("test relatedEntityType") {
            // uncomment below to test the property
            //modelInstance.relatedEntityType shouldBe ("TODO")
        }

    }
}
