/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.EventResponseDto

class EventResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EventResponseDto
        //val modelInstance = EventResponseDto()

        // to test the property `id` - Unique identifier for the event
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `merchantId` - ID of the merchant this event belongs to
        should("test merchantId") {
            // uncomment below to test the property
            //modelInstance.merchantId shouldBe ("TODO")
        }

        // to test the property `webhookEndpointId` - ID of the webhook endpoint this event was sent to
        should("test webhookEndpointId") {
            // uncomment below to test the property
            //modelInstance.webhookEndpointId shouldBe ("TODO")
        }

        // to test the property `type` - Event type name
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property ``data`` - Event data payload
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `status` - Current delivery status of the event
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `attempts` - Number of delivery attempts
        should("test attempts") {
            // uncomment below to test the property
            //modelInstance.attempts shouldBe ("TODO")
        }

        // to test the property `createdAt` - Timestamp when the event was created
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - Timestamp when the event was last updated
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `relatedEntityId` - ID of the related entity
        should("test relatedEntityId") {
            // uncomment below to test the property
            //modelInstance.relatedEntityId shouldBe ("TODO")
        }

        // to test the property `relatedEntityType` - Type of the related entity
        should("test relatedEntityType") {
            // uncomment below to test the property
            //modelInstance.relatedEntityType shouldBe ("TODO")
        }

        // to test the property `lastAttemptAt` - Timestamp of the last delivery attempt
        should("test lastAttemptAt") {
            // uncomment below to test the property
            //modelInstance.lastAttemptAt shouldBe ("TODO")
        }

        // to test the property `nextRetryAt` - Timestamp for the next retry attempt
        should("test nextRetryAt") {
            // uncomment below to test the property
            //modelInstance.nextRetryAt shouldBe ("TODO")
        }

        // to test the property `deliveredAt` - Timestamp when the event was successfully delivered
        should("test deliveredAt") {
            // uncomment below to test the property
            //modelInstance.deliveredAt shouldBe ("TODO")
        }

    }
}
