/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.FileDto

class FileDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FileDto
        //val modelInstance = FileDto()

        // to test the property `id` - Unique identifier
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `key`
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `bucket`
        should("test bucket") {
            // uncomment below to test the property
            //modelInstance.bucket shouldBe ("TODO")
        }

        // to test the property `filename`
        should("test filename") {
            // uncomment below to test the property
            //modelInstance.filename shouldBe ("TODO")
        }

        // to test the property `mimeType`
        should("test mimeType") {
            // uncomment below to test the property
            //modelInstance.mimeType shouldBe ("TODO")
        }

        // to test the property `propertySize`
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `isPublic`
        should("test isPublic") {
            // uncomment below to test the property
            //modelInstance.isPublic shouldBe ("TODO")
        }

        // to test the property `deletedAt`
        should("test deletedAt") {
            // uncomment below to test the property
            //modelInstance.deletedAt shouldBe ("TODO")
        }

        // to test the property `checksum`
        should("test checksum") {
            // uncomment below to test the property
            //modelInstance.checksum shouldBe ("TODO")
        }

        // to test the property `relatedEntityId`
        should("test relatedEntityId") {
            // uncomment below to test the property
            //modelInstance.relatedEntityId shouldBe ("TODO")
        }

        // to test the property `relatedEntityType`
        should("test relatedEntityType") {
            // uncomment below to test the property
            //modelInstance.relatedEntityType shouldBe ("TODO")
        }

        // to test the property `uploadedById`
        should("test uploadedById") {
            // uncomment below to test the property
            //modelInstance.uploadedById shouldBe ("TODO")
        }

    }
}
