/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.IVeriHealthCheckResponseDto

class IVeriHealthCheckResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IVeriHealthCheckResponseDto
        //val modelInstance = IVeriHealthCheckResponseDto()

        // to test the property `status` - Service health status
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `timestamp` - Current server timestamp in ISO format
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

    }
}
