/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.LinkSocialDto

class LinkSocialDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LinkSocialDto
        //val modelInstance = LinkSocialDto()

        // to test the property `provider` - The social provider to link
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `accessToken` - Access token from provider
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `refreshToken` - Refresh token from provider
        should("test refreshToken") {
            // uncomment below to test the property
            //modelInstance.refreshToken shouldBe ("TODO")
        }

        // to test the property `idToken` - ID token from provider
        should("test idToken") {
            // uncomment below to test the property
            //modelInstance.idToken shouldBe ("TODO")
        }

        // to test the property `expiresAt` - Token expiration time
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

    }
}
