/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.ListMembersResponseDto
import com.cashful.kotlin.sdk.model.MemberDto

class ListMembersResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListMembersResponseDto
        //val modelInstance = ListMembersResponseDto()

        // to test the property `members` - List of organization members
        should("test members") {
            // uncomment below to test the property
            //modelInstance.members shouldBe ("TODO")
        }

    }
}
