/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.ListSessionsResponseDto
import com.cashful.kotlin.sdk.model.SessionDto

class ListSessionsResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListSessionsResponseDto
        //val modelInstance = ListSessionsResponseDto()

        // to test the property `sessions` - List of user sessions
        should("test sessions") {
            // uncomment below to test the property
            //modelInstance.sessions shouldBe ("TODO")
        }

    }
}
