/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.ListOrganizationsResponseDto
import com.cashful.kotlin.sdk.model.Organization

class ListOrganizationsResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListOrganizationsResponseDto
        //val modelInstance = ListOrganizationsResponseDto()

        // to test the property `organizations` - List of organizations
        should("test organizations") {
            // uncomment below to test the property
            //modelInstance.organizations shouldBe ("TODO")
        }

    }
}
