/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.ListEventsResponseDto
import com.cashful.kotlin.sdk.model.EventResponseDto
import com.cashful.kotlin.sdk.model.PaginationResponseDto

class ListEventsResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListEventsResponseDto
        //val modelInstance = ListEventsResponseDto()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `pagination`
        should("test pagination") {
            // uncomment below to test the property
            //modelInstance.pagination shouldBe ("TODO")
        }

    }
}
