/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.ListUsersResponseDto

class ListUsersResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListUsersResponseDto
        //val modelInstance = ListUsersResponseDto()

        // to test the property `users` - List of users
        should("test users") {
            // uncomment below to test the property
            //modelInstance.users shouldBe ("TODO")
        }

    }
}
