/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.PaymentMethodResponseDto

class PaymentMethodResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentMethodResponseDto
        //val modelInstance = PaymentMethodResponseDto()

        // to test the property `id` - Unique payment method identifier
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `customerId` - Customer ID this payment method belongs to
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `type` - Payment method type (e.g., card, mobile_money)
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `provider` - Payment provider name (e.g., iveri, mpesa)
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `isDefault` - Whether this is the default payment method
        should("test isDefault") {
            // uncomment below to test the property
            //modelInstance.isDefault shouldBe ("TODO")
        }

        // to test the property `createdAt` - When the payment method was created
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - When the payment method was last updated
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `brand` - Card brand (e.g., Visa, Mastercard)
        should("test brand") {
            // uncomment below to test the property
            //modelInstance.brand shouldBe ("TODO")
        }

        // to test the property `last4` - Last 4 digits of card number
        should("test last4") {
            // uncomment below to test the property
            //modelInstance.last4 shouldBe ("TODO")
        }

        // to test the property `expiryMonth` - Card expiry month (1-12)
        should("test expiryMonth") {
            // uncomment below to test the property
            //modelInstance.expiryMonth shouldBe ("TODO")
        }

        // to test the property `expiryYear` - Card expiry year
        should("test expiryYear") {
            // uncomment below to test the property
            //modelInstance.expiryYear shouldBe ("TODO")
        }

        // to test the property `phoneNumber` - Phone number for mobile money
        should("test phoneNumber") {
            // uncomment below to test the property
            //modelInstance.phoneNumber shouldBe ("TODO")
        }

    }
}
