/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.PresignedUploadResponseDto

class PresignedUploadResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PresignedUploadResponseDto
        //val modelInstance = PresignedUploadResponseDto()

        // to test the property `uploadUrl` - Presigned upload URL
        should("test uploadUrl") {
            // uncomment below to test the property
            //modelInstance.uploadUrl shouldBe ("TODO")
        }

        // to test the property `fileId` - File ID for tracking
        should("test fileId") {
            // uncomment below to test the property
            //modelInstance.fileId shouldBe ("TODO")
        }

        // to test the property `key` - S3 object key
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `expiresAt` - URL expiration time
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

    }
}
