/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.RefreshTokenDto

class RefreshTokenDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RefreshTokenDto
        //val modelInstance = RefreshTokenDto()

        // to test the property `refreshToken` - The refresh token
        should("test refreshToken") {
            // uncomment below to test the property
            //modelInstance.refreshToken shouldBe ("TODO")
        }

        // to test the property `rotate` - Whether to rotate the token
        should("test rotate") {
            // uncomment below to test the property
            //modelInstance.rotate shouldBe ("TODO")
        }

    }
}
