/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.SessionDto

class SessionDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SessionDto
        //val modelInstance = SessionDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `ipAddress`
        should("test ipAddress") {
            // uncomment below to test the property
            //modelInstance.ipAddress shouldBe ("TODO")
        }

        // to test the property `userAgent`
        should("test userAgent") {
            // uncomment below to test the property
            //modelInstance.userAgent shouldBe ("TODO")
        }

    }
}
