/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.TimeframeMetricsDto
import com.cashful.kotlin.sdk.model.DailyBreakdownDto
import com.cashful.kotlin.sdk.model.MetricStatsDto

class TimeframeMetricsDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TimeframeMetricsDto
        //val modelInstance = TimeframeMetricsDto()

        // to test the property `daily`
        should("test daily") {
            // uncomment below to test the property
            //modelInstance.daily shouldBe ("TODO")
        }

        // to test the property `weekly`
        should("test weekly") {
            // uncomment below to test the property
            //modelInstance.weekly shouldBe ("TODO")
        }

        // to test the property `monthly`
        should("test monthly") {
            // uncomment below to test the property
            //modelInstance.monthly shouldBe ("TODO")
        }

        // to test the property `breakdown` - Day-by-day breakdown for the last 30 days
        should("test breakdown") {
            // uncomment below to test the property
            //modelInstance.breakdown shouldBe ("TODO")
        }

    }
}
