/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cashful.kotlin.sdk.model.UpdateOrganizationKycDto

class UpdateOrganizationKycDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateOrganizationKycDto
        //val modelInstance = UpdateOrganizationKycDto()

        // to test the property `idNumber`
        should("test idNumber") {
            // uncomment below to test the property
            //modelInstance.idNumber shouldBe ("TODO")
        }

        // to test the property `companyRegistrationName`
        should("test companyRegistrationName") {
            // uncomment below to test the property
            //modelInstance.companyRegistrationName shouldBe ("TODO")
        }

        // to test the property `companyRegistrationNumber`
        should("test companyRegistrationNumber") {
            // uncomment below to test the property
            //modelInstance.companyRegistrationNumber shouldBe ("TODO")
        }

        // to test the property `companyTradingName`
        should("test companyTradingName") {
            // uncomment below to test the property
            //modelInstance.companyTradingName shouldBe ("TODO")
        }

        // to test the property `vatRegistrationNumber`
        should("test vatRegistrationNumber") {
            // uncomment below to test the property
            //modelInstance.vatRegistrationNumber shouldBe ("TODO")
        }

        // to test the property `industry`
        should("test industry") {
            // uncomment below to test the property
            //modelInstance.industry shouldBe ("TODO")
        }

        // to test the property `subIndustry`
        should("test subIndustry") {
            // uncomment below to test the property
            //modelInstance.subIndustry shouldBe ("TODO")
        }

        // to test the property `estimatedAnnualTurnover`
        should("test estimatedAnnualTurnover") {
            // uncomment below to test the property
            //modelInstance.estimatedAnnualTurnover shouldBe ("TODO")
        }

        // to test the property `businessDescription`
        should("test businessDescription") {
            // uncomment below to test the property
            //modelInstance.businessDescription shouldBe ("TODO")
        }

        // to test the property `companyEmail`
        should("test companyEmail") {
            // uncomment below to test the property
            //modelInstance.companyEmail shouldBe ("TODO")
        }

        // to test the property `companyContactNumber`
        should("test companyContactNumber") {
            // uncomment below to test the property
            //modelInstance.companyContactNumber shouldBe ("TODO")
        }

        // to test the property `website`
        should("test website") {
            // uncomment below to test the property
            //modelInstance.website shouldBe ("TODO")
        }

        // to test the property `socialMedia`
        should("test socialMedia") {
            // uncomment below to test the property
            //modelInstance.socialMedia shouldBe ("TODO")
        }

        // to test the property `accountContactNumber`
        should("test accountContactNumber") {
            // uncomment below to test the property
            //modelInstance.accountContactNumber shouldBe ("TODO")
        }

        // to test the property `customerSupportContactNumber`
        should("test customerSupportContactNumber") {
            // uncomment below to test the property
            //modelInstance.customerSupportContactNumber shouldBe ("TODO")
        }

        // to test the property `customerSupportEscalationContactNumber`
        should("test customerSupportEscalationContactNumber") {
            // uncomment below to test the property
            //modelInstance.customerSupportEscalationContactNumber shouldBe ("TODO")
        }

        // to test the property `emergencyContactNumber`
        should("test emergencyContactNumber") {
            // uncomment below to test the property
            //modelInstance.emergencyContactNumber shouldBe ("TODO")
        }

        // to test the property `streetAddress`
        should("test streetAddress") {
            // uncomment below to test the property
            //modelInstance.streetAddress shouldBe ("TODO")
        }

        // to test the property `apartment`
        should("test apartment") {
            // uncomment below to test the property
            //modelInstance.apartment shouldBe ("TODO")
        }

        // to test the property `suburb`
        should("test suburb") {
            // uncomment below to test the property
            //modelInstance.suburb shouldBe ("TODO")
        }

        // to test the property `city`
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `postalCode`
        should("test postalCode") {
            // uncomment below to test the property
            //modelInstance.postalCode shouldBe ("TODO")
        }

        // to test the property `bank`
        should("test bank") {
            // uncomment below to test the property
            //modelInstance.bank shouldBe ("TODO")
        }

        // to test the property `accountType`
        should("test accountType") {
            // uncomment below to test the property
            //modelInstance.accountType shouldBe ("TODO")
        }

        // to test the property `accountName`
        should("test accountName") {
            // uncomment below to test the property
            //modelInstance.accountName shouldBe ("TODO")
        }

        // to test the property `accountNumber`
        should("test accountNumber") {
            // uncomment below to test the property
            //modelInstance.accountNumber shouldBe ("TODO")
        }

        // to test the property `branchCode`
        should("test branchCode") {
            // uncomment below to test the property
            //modelInstance.branchCode shouldBe ("TODO")
        }

        // to test the property `isSouthAfricanResidentAccount`
        should("test isSouthAfricanResidentAccount") {
            // uncomment below to test the property
            //modelInstance.isSouthAfricanResidentAccount shouldBe ("TODO")
        }

        // to test the property `certificateOfIncorporation`
        should("test certificateOfIncorporation") {
            // uncomment below to test the property
            //modelInstance.certificateOfIncorporation shouldBe ("TODO")
        }

        // to test the property `identityDocuments`
        should("test identityDocuments") {
            // uncomment below to test the property
            //modelInstance.identityDocuments shouldBe ("TODO")
        }

        // to test the property `bankAccountConfirmationLetter`
        should("test bankAccountConfirmationLetter") {
            // uncomment below to test the property
            //modelInstance.bankAccountConfirmationLetter shouldBe ("TODO")
        }

        // to test the property `proofOfBusinessAddress`
        should("test proofOfBusinessAddress") {
            // uncomment below to test the property
            //modelInstance.proofOfBusinessAddress shouldBe ("TODO")
        }

        // to test the property `ecnsLicense`
        should("test ecnsLicense") {
            // uncomment below to test the property
            //modelInstance.ecnsLicense shouldBe ("TODO")
        }

        // to test the property `termsAccepted`
        should("test termsAccepted") {
            // uncomment below to test the property
            //modelInstance.termsAccepted shouldBe ("TODO")
        }

        // to test the property `acceptedAt`
        should("test acceptedAt") {
            // uncomment below to test the property
            //modelInstance.acceptedAt shouldBe ("TODO")
        }

        // to test the property `currentStep`
        should("test currentStep") {
            // uncomment below to test the property
            //modelInstance.currentStep shouldBe ("TODO")
        }

        // to test the property `isCompleted`
        should("test isCompleted") {
            // uncomment below to test the property
            //modelInstance.isCompleted shouldBe ("TODO")
        }

        // to test the property `completionScore`
        should("test completionScore") {
            // uncomment below to test the property
            //modelInstance.completionScore shouldBe ("TODO")
        }

    }
}
