/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param balance Current merchant balance in cents/smallest unit
 * @param customers Total number of customers
 * @param transactions Total number of transactions
 * @param members Total number of organization members
 */
@Serializable

data class AnalyticsSummaryDto (

    /* Current merchant balance in cents/smallest unit */
    @Contextual @SerialName(value = "balance")
    val balance: java.math.BigDecimal,

    /* Total number of customers */
    @Contextual @SerialName(value = "customers")
    val customers: java.math.BigDecimal,

    /* Total number of transactions */
    @Contextual @SerialName(value = "transactions")
    val transactions: java.math.BigDecimal,

    /* Total number of organization members */
    @Contextual @SerialName(value = "members")
    val members: java.math.BigDecimal

) {


}

