/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import com.cashful.kotlin.sdk.model.SessionUserDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status Indicates if request was successful
 * @param message Status message of email change process
 * @param user User object
 */
@Serializable

data class ChangeEmailResponseDto (

    /* Indicates if request was successful */
    @SerialName(value = "status")
    val status: kotlin.Boolean,

    /* Status message of email change process */
    @SerialName(value = "message")
    val message: ChangeEmailResponseDto.Message? = null,

    /* User object */
    @SerialName(value = "user")
    val user: SessionUserDto? = null

) {

    /**
     * Status message of email change process
     *
     * Values: Email_updated,Verification_email_sent
     */
    @Serializable
    enum class Message(val value: kotlin.String) {
        @SerialName(value = "Email updated") Email_updated("Email updated"),
        @SerialName(value = "Verification email sent") Verification_email_sent("Verification email sent");
    }

}

