/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import com.cashful.kotlin.sdk.model.SessionUserDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param user User object
 * @param token New session token if other sessions were revoked
 */
@Serializable

data class ChangePasswordResponseDto (

    /* User object */
    @SerialName(value = "user")
    val user: SessionUserDto,

    /* New session token if other sessions were revoked */
    @SerialName(value = "token")
    val token: kotlin.String? = null

) {


}

