/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param customerId The unique identifier of the customer
 * @param productId The unique identifier of the product
 * @param amount The amount in the smallest currency unit
 * @param currency The three-letter ISO 4217 currency code
 * @param merchantId The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
 * @param quantity The quantity of items in the purchase
 */
@Serializable

data class CreatePurchaseDto (

    /* The unique identifier of the customer */
    @SerialName(value = "customerId")
    val customerId: kotlin.String,

    /* The unique identifier of the product */
    @SerialName(value = "productId")
    val productId: kotlin.String,

    /* The amount in the smallest currency unit */
    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal,

    /* The three-letter ISO 4217 currency code */
    @SerialName(value = "currency")
    val currency: kotlin.String,

    /* The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant. */
    @SerialName(value = "merchantId")
    val merchantId: kotlin.String? = null,

    /* The quantity of items in the purchase */
    @Contextual @SerialName(value = "quantity")
    val quantity: java.math.BigDecimal? = null

) {


}

