/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param phoneNumber The phone number of the customer
 * @param metadata Optional custom metadata
 * @param merchantId The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
 * @param email The email address of the customer
 * @param name The full name of the customer
 */
@Serializable

data class CreateCustomerDto (

    /* The phone number of the customer */
    @SerialName(value = "phoneNumber")
    val phoneNumber: kotlin.String,

    /* Optional custom metadata */
    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant. */
    @SerialName(value = "merchantId")
    val merchantId: kotlin.String? = null,

    /* The email address of the customer */
    @SerialName(value = "email")
    val email: kotlin.String? = null,

    /* The full name of the customer */
    @SerialName(value = "name")
    val name: kotlin.String? = null

) {


}

