/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param fromCustomerId The unique identifier of the customer sending the transfer
 * @param toCustomerId The unique identifier of the customer receiving the transfer
 * @param amount The amount to transfer in the smallest currency unit
 * @param currency The three-letter ISO 4217 currency code
 * @param merchantId The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
 * @param description Optional description for the transfer
 */
@Serializable

data class CreateTransferDto (

    /* The unique identifier of the customer sending the transfer */
    @SerialName(value = "fromCustomerId")
    val fromCustomerId: kotlin.String,

    /* The unique identifier of the customer receiving the transfer */
    @SerialName(value = "toCustomerId")
    val toCustomerId: kotlin.String,

    /* The amount to transfer in the smallest currency unit */
    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal,

    /* The three-letter ISO 4217 currency code */
    @SerialName(value = "currency")
    val currency: kotlin.String,

    /* The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant. */
    @SerialName(value = "merchantId")
    val merchantId: kotlin.String? = null,

    /* Optional description for the transfer */
    @SerialName(value = "description")
    val description: kotlin.String? = null

) {


}

