/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param merchantId The ID of the merchant
 * @param amount The initial balance amount
 * @param currency The currency for the balance
 */
@Serializable

data class CreateBalanceDto (

    /* The ID of the merchant */
    @SerialName(value = "merchantId")
    val merchantId: kotlin.String,

    /* The initial balance amount */
    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal,

    /* The currency for the balance */
    @SerialName(value = "currency")
    val currency: kotlin.String

) {


}

