/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique identifier
 * @param createdAt 
 * @param updatedAt 
 * @param merchantId 
 * @param email 
 * @param metadata 
 * @param deletedAt 
 * @param name 
 */
@Serializable

data class CustomerResponseDto (

    /* Unique identifier */
    @SerialName(value = "id")
    val id: kotlin.String,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "merchantId")
    val merchantId: kotlin.String,

    @SerialName(value = "email")
    val email: kotlin.String,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Contextual @SerialName(value = "deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null

) {


}

