/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique identifier
 * @param createdAt 
 * @param updatedAt 
 * @param customerId 
 * @param amount 
 * @param currency 
 * @param available 
 * @param pending 
 * @param deletedAt 
 * @param merchantId 
 */
@Serializable

data class CustomerBalanceDto (

    /* Unique identifier */
    @SerialName(value = "id")
    val id: kotlin.String,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "customerId")
    val customerId: kotlin.String,

    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal,

    @SerialName(value = "currency")
    val currency: kotlin.String,

    @Contextual @SerialName(value = "available")
    val available: java.math.BigDecimal,

    @Contextual @SerialName(value = "pending")
    val pending: java.math.BigDecimal,

    @Contextual @SerialName(value = "deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "merchantId")
    val merchantId: kotlin.String? = null

) {


}

