/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status Payment status after 3DS authentication
 * @param merchantReference Merchant reference for the payment
 * @param paymentIntentId Payment intent ID
 * @param transactionId Transaction ID if payment succeeded
 * @param authCode Authorization code from payment gateway
 * @param reason Reason for failure if payment failed
 * @param amount Payment amount in smallest currency unit
 * @param currency Currency code
 */
@Serializable

data class DebitReturnResponseDto (

    /* Payment status after 3DS authentication */
    @SerialName(value = "status")
    val status: DebitReturnResponseDto.Status,

    /* Merchant reference for the payment */
    @SerialName(value = "merchantReference")
    val merchantReference: kotlin.String,

    /* Payment intent ID */
    @SerialName(value = "paymentIntentId")
    val paymentIntentId: kotlin.String? = null,

    /* Transaction ID if payment succeeded */
    @SerialName(value = "transactionId")
    val transactionId: kotlin.String? = null,

    /* Authorization code from payment gateway */
    @SerialName(value = "authCode")
    val authCode: kotlin.String? = null,

    /* Reason for failure if payment failed */
    @SerialName(value = "reason")
    val reason: kotlin.String? = null,

    /* Payment amount in smallest currency unit */
    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal? = null,

    /* Currency code */
    @SerialName(value = "currency")
    val currency: kotlin.String? = null

) {

    /**
     * Payment status after 3DS authentication
     *
     * Values: succeeded,failed,pending
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "succeeded") succeeded("succeeded"),
        @SerialName(value = "failed") failed("failed"),
        @SerialName(value = "pending") pending("pending");
    }

}

