/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param provider The provider to get token for
 * @param forceRefresh Whether to force token refresh
 */
@Serializable

data class GetAccessTokenDto (

    /* The provider to get token for */
    @SerialName(value = "provider")
    val provider: kotlin.String? = null,

    /* Whether to force token refresh */
    @SerialName(value = "forceRefresh")
    val forceRefresh: kotlin.Boolean? = null

) {


}

