/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import com.cashful.kotlin.sdk.model.PaginationResponseDto
import com.cashful.kotlin.sdk.model.PaymentLinkResponseDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `data` 
 * @param pagination 
 */
@Serializable

data class ListPaymentLinksResponseDto (

    @SerialName(value = "data")
    val `data`: kotlin.collections.List<PaymentLinkResponseDto>,

    @SerialName(value = "pagination")
    val pagination: PaginationResponseDto

) {


}

