/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model

import com.cashful.kotlin.sdk.model.SessionDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param sessions List of user sessions
 */
@Serializable

data class ListSessionsResponseDto (

    /* List of user sessions */
    @SerialName(value = "sessions")
    val sessions: kotlin.collections.List<SessionDto>

) {


}

