/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param limit Maximum number of items returned in this response
 * @param offset Number of items skipped before this response
 * @param total Total number of items available
 * @param hasMore Whether there are more items available beyond this response
 */
@Serializable

data class PaginationResponseDto (

    /* Maximum number of items returned in this response */
    @Contextual @SerialName(value = "limit")
    val limit: java.math.BigDecimal,

    /* Number of items skipped before this response */
    @Contextual @SerialName(value = "offset")
    val offset: java.math.BigDecimal,

    /* Total number of items available */
    @Contextual @SerialName(value = "total")
    val total: java.math.BigDecimal,

    /* Whether there are more items available beyond this response */
    @SerialName(value = "hasMore")
    val hasMore: kotlin.Boolean

) {


}

