/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param downloadUrl Presigned download URL
 * @param expiresAt URL expiration time
 */
@Serializable

data class PresignedDownloadResponseDto (

    /* Presigned download URL */
    @SerialName(value = "downloadUrl")
    val downloadUrl: kotlin.String,

    /* URL expiration time */
    @Contextual @SerialName(value = "expiresAt")
    val expiresAt: java.time.OffsetDateTime

) {


}

