/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param phoneNumber The phone number to send reset to
 * @param callbackURL Callback URL for password reset
 */
@Serializable

data class RequestPhonePasswordResetDto (

    /* The phone number to send reset to */
    @SerialName(value = "phoneNumber")
    val phoneNumber: kotlin.String,

    /* Callback URL for password reset */
    @SerialName(value = "callbackURL")
    val callbackURL: kotlin.String? = null

) {


}

