/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status Indicates if email was sent successfully
 */
@Serializable

data class SendVerificationEmailResponseDto (

    /* Indicates if email was sent successfully */
    @SerialName(value = "status")
    val status: kotlin.Boolean

) {


}

