/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param email 
 * @param emailVerified 
 * @param name 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class SessionUserDto (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "emailVerified")
    val emailVerified: kotlin.Boolean,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime

) {


}

