/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email The email address of the user
 * @param password The password for the user account
 */
@Serializable

data class SignInDto (

    /* The email address of the user */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* The password for the user account */
    @SerialName(value = "password")
    val password: kotlin.String

) {


}

