/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name The name of the user
 * @param email The email address of the user
 * @param password The password for the user account
 * @param image Optional URL to the user's profile image
 * @param callbackURL Optional callback URL after successful sign-up
 * @param rememberMe Optional flag to indicate if the user should be remembered
 */
@Serializable

data class SignUpDto (

    /* The name of the user */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The email address of the user */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* The password for the user account */
    @SerialName(value = "password")
    val password: kotlin.String,

    /* Optional URL to the user's profile image */
    @SerialName(value = "image")
    val image: kotlin.String? = null,

    /* Optional callback URL after successful sign-up */
    @SerialName(value = "callbackURL")
    val callbackURL: kotlin.String? = null,

    /* Optional flag to indicate if the user should be remembered */
    @SerialName(value = "rememberMe")
    val rememberMe: kotlin.Boolean? = null

) {


}

