/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param metadata Optional custom metadata
 * @param url The URL where webhook events will be sent
 * @param events Array of event types to listen for
 * @param active Whether the webhook endpoint is active
 */
@Serializable

data class UpdateWebhookEndpointDto (

    /* Optional custom metadata */
    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* The URL where webhook events will be sent */
    @SerialName(value = "url")
    val url: kotlin.String? = null,

    /* Array of event types to listen for */
    @SerialName(value = "events")
    val events: kotlin.collections.List<kotlin.String>? = null,

    /* Whether the webhook endpoint is active */
    @SerialName(value = "active")
    val active: kotlin.Boolean? = null

) {


}

