/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.kotlin.sdk.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param merchantId 
 * @param url 
 * @param events 
 * @param active 
 * @param metadata 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class WebhookEndpointResponseDto (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "merchantId")
    val merchantId: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "events")
    val events: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "active")
    val active: kotlin.Boolean,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime

) {


}

