/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.cashful.model.BadRequestResponseDto
import com.cashful.model.CreateOrganizationComplianceDto
import com.cashful.model.InternalServerErrorResponseDto
import com.cashful.model.NotFoundResponseDto
import com.cashful.model.OrganizationComplianceResponseDto
import com.cashful.model.UnauthorizedResponseDto
import com.cashful.model.UpdateOrganizationComplianceDto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.cashful.infrastructure.ApiClient
import com.cashful.infrastructure.ApiResponse
import com.cashful.infrastructure.ClientException
import com.cashful.infrastructure.ClientError
import com.cashful.infrastructure.ServerException
import com.cashful.infrastructure.ServerError
import com.cashful.infrastructure.MultiValueMap
import com.cashful.infrastructure.PartConfig
import com.cashful.infrastructure.RequestConfig
import com.cashful.infrastructure.RequestMethod
import com.cashful.infrastructure.ResponseType
import com.cashful.infrastructure.Success
import com.cashful.infrastructure.toMultiValue

class ComplianceApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.cashful.africa")
        }
    }

    /**
     * POST /api/canary/compliance
     * Create Compliance info
     * 
     * @param createOrganizationComplianceDto 
     * @return OrganizationComplianceResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createCompliance(createOrganizationComplianceDto: CreateOrganizationComplianceDto) : OrganizationComplianceResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = createComplianceWithHttpInfo(createOrganizationComplianceDto = createOrganizationComplianceDto)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as OrganizationComplianceResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/canary/compliance
     * Create Compliance info
     * 
     * @param createOrganizationComplianceDto 
     * @return ApiResponse<OrganizationComplianceResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createComplianceWithHttpInfo(createOrganizationComplianceDto: CreateOrganizationComplianceDto) : ApiResponse<OrganizationComplianceResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createComplianceRequestConfig(createOrganizationComplianceDto = createOrganizationComplianceDto)

        return@withContext request<CreateOrganizationComplianceDto, OrganizationComplianceResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createCompliance
     *
     * @param createOrganizationComplianceDto 
     * @return RequestConfig
     */
    fun createComplianceRequestConfig(createOrganizationComplianceDto: CreateOrganizationComplianceDto) : RequestConfig<CreateOrganizationComplianceDto> {
        val localVariableBody = createOrganizationComplianceDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/canary/compliance",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/canary/compliance
     * Get Compliance info for organization
     * 
     * @param organizationId 
     * @return OrganizationComplianceResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getCompliance(organizationId: kotlin.String) : OrganizationComplianceResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = getComplianceWithHttpInfo(organizationId = organizationId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as OrganizationComplianceResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/canary/compliance
     * Get Compliance info for organization
     * 
     * @param organizationId 
     * @return ApiResponse<OrganizationComplianceResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getComplianceWithHttpInfo(organizationId: kotlin.String) : ApiResponse<OrganizationComplianceResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getComplianceRequestConfig(organizationId = organizationId)

        return@withContext request<Unit, OrganizationComplianceResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCompliance
     *
     * @param organizationId 
     * @return RequestConfig
     */
    fun getComplianceRequestConfig(organizationId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("organizationId", listOf(organizationId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/canary/compliance",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/canary/compliance/{id}
     * Update Compliance info
     * 
     * @param id 
     * @param updateOrganizationComplianceDto 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateCompliance(id: kotlin.String, updateOrganizationComplianceDto: UpdateOrganizationComplianceDto) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = updateComplianceWithHttpInfo(id = id, updateOrganizationComplianceDto = updateOrganizationComplianceDto)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/canary/compliance/{id}
     * Update Compliance info
     * 
     * @param id 
     * @param updateOrganizationComplianceDto 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateComplianceWithHttpInfo(id: kotlin.String, updateOrganizationComplianceDto: UpdateOrganizationComplianceDto) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateComplianceRequestConfig(id = id, updateOrganizationComplianceDto = updateOrganizationComplianceDto)

        return@withContext request<UpdateOrganizationComplianceDto, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateCompliance
     *
     * @param id 
     * @param updateOrganizationComplianceDto 
     * @return RequestConfig
     */
    fun updateComplianceRequestConfig(id: kotlin.String, updateOrganizationComplianceDto: UpdateOrganizationComplianceDto) : RequestConfig<UpdateOrganizationComplianceDto> {
        val localVariableBody = updateOrganizationComplianceDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/canary/compliance/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
