/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.cashful.model.BadRequestResponseDto
import com.cashful.model.CreateProductDto
import com.cashful.model.InternalServerErrorResponseDto
import com.cashful.model.ListProductsResponseDto
import com.cashful.model.NotFoundResponseDto
import com.cashful.model.ProductResponseDto
import com.cashful.model.RetrieveMultipleProductsDto
import com.cashful.model.UnauthorizedResponseDto
import com.cashful.model.UpdateProductDto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.cashful.infrastructure.ApiClient
import com.cashful.infrastructure.ApiResponse
import com.cashful.infrastructure.ClientException
import com.cashful.infrastructure.ClientError
import com.cashful.infrastructure.ServerException
import com.cashful.infrastructure.ServerError
import com.cashful.infrastructure.MultiValueMap
import com.cashful.infrastructure.PartConfig
import com.cashful.infrastructure.RequestConfig
import com.cashful.infrastructure.RequestMethod
import com.cashful.infrastructure.ResponseType
import com.cashful.infrastructure.Success
import com.cashful.infrastructure.toMultiValue

class ProductsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.cashful.africa")
        }
    }

    /**
     * POST /api/canary/products
     * Create Product
     * Defines a product in the merchant&#39;s catalog (e.g., \&quot;Airtime,\&quot; \&quot;Data\&quot;).
     * @param createProductDto Product details
     * @return ProductResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createProduct(createProductDto: CreateProductDto) : ProductResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = createProductWithHttpInfo(createProductDto = createProductDto)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ProductResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/canary/products
     * Create Product
     * Defines a product in the merchant&#39;s catalog (e.g., \&quot;Airtime,\&quot; \&quot;Data\&quot;).
     * @param createProductDto Product details
     * @return ApiResponse<ProductResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createProductWithHttpInfo(createProductDto: CreateProductDto) : ApiResponse<ProductResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createProductRequestConfig(createProductDto = createProductDto)

        return@withContext request<CreateProductDto, ProductResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createProduct
     *
     * @param createProductDto Product details
     * @return RequestConfig
     */
    fun createProductRequestConfig(createProductDto: CreateProductDto) : RequestConfig<CreateProductDto> {
        val localVariableBody = createProductDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/canary/products",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/canary/products
     * List Products
     * Retrieves all products in the merchant&#39;s catalog.
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @param merchantId The ID of the merchant whose products are being requested. If not provided, the products of the authenticated merchant will be returned. (optional)
     * @param active Filter by active status (optional)
     * @return ListProductsResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listProducts(limit: java.math.BigDecimal? = null, offset: java.math.BigDecimal? = null, merchantId: kotlin.String? = null, active: kotlin.Boolean? = null) : ListProductsResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = listProductsWithHttpInfo(limit = limit, offset = offset, merchantId = merchantId, active = active)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ListProductsResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/canary/products
     * List Products
     * Retrieves all products in the merchant&#39;s catalog.
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @param merchantId The ID of the merchant whose products are being requested. If not provided, the products of the authenticated merchant will be returned. (optional)
     * @param active Filter by active status (optional)
     * @return ApiResponse<ListProductsResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listProductsWithHttpInfo(limit: java.math.BigDecimal?, offset: java.math.BigDecimal?, merchantId: kotlin.String?, active: kotlin.Boolean?) : ApiResponse<ListProductsResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listProductsRequestConfig(limit = limit, offset = offset, merchantId = merchantId, active = active)

        return@withContext request<Unit, ListProductsResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listProducts
     *
     * @param limit Maximum number of records to return (optional)
     * @param offset Number of records to skip (optional)
     * @param merchantId The ID of the merchant whose products are being requested. If not provided, the products of the authenticated merchant will be returned. (optional)
     * @param active Filter by active status (optional)
     * @return RequestConfig
     */
    fun listProductsRequestConfig(limit: java.math.BigDecimal?, offset: java.math.BigDecimal?, merchantId: kotlin.String?, active: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
                if (merchantId != null) {
                    put("merchantId", listOf(merchantId.toString()))
                }
                if (active != null) {
                    put("active", listOf(active.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/canary/products",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/canary/products/multiple
     * Retrieve Multiple Products by ID
     * Retrieves multiple products using the provided ID&#39;s with a maximum of 50 IDs.
     * @param retrieveMultipleProductsDto List of product IDs
     * @return kotlin.collections.List<ProductResponseDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun retrieveMultipleProducts(retrieveMultipleProductsDto: RetrieveMultipleProductsDto) : kotlin.collections.List<ProductResponseDto> = withContext(Dispatchers.IO) {
        val localVarResponse = retrieveMultipleProductsWithHttpInfo(retrieveMultipleProductsDto = retrieveMultipleProductsDto)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ProductResponseDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/canary/products/multiple
     * Retrieve Multiple Products by ID
     * Retrieves multiple products using the provided ID&#39;s with a maximum of 50 IDs.
     * @param retrieveMultipleProductsDto List of product IDs
     * @return ApiResponse<kotlin.collections.List<ProductResponseDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun retrieveMultipleProductsWithHttpInfo(retrieveMultipleProductsDto: RetrieveMultipleProductsDto) : ApiResponse<kotlin.collections.List<ProductResponseDto>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = retrieveMultipleProductsRequestConfig(retrieveMultipleProductsDto = retrieveMultipleProductsDto)

        return@withContext request<RetrieveMultipleProductsDto, kotlin.collections.List<ProductResponseDto>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation retrieveMultipleProducts
     *
     * @param retrieveMultipleProductsDto List of product IDs
     * @return RequestConfig
     */
    fun retrieveMultipleProductsRequestConfig(retrieveMultipleProductsDto: RetrieveMultipleProductsDto) : RequestConfig<RetrieveMultipleProductsDto> {
        val localVariableBody = retrieveMultipleProductsDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/canary/products/multiple",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/canary/products/{id}
     * Retrieve Product
     * Retrieves a single product by ID.
     * @param id The unique identifier of the product
     * @return ProductResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun retrieveProduct(id: kotlin.String) : ProductResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = retrieveProductWithHttpInfo(id = id)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ProductResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/canary/products/{id}
     * Retrieve Product
     * Retrieves a single product by ID.
     * @param id The unique identifier of the product
     * @return ApiResponse<ProductResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun retrieveProductWithHttpInfo(id: kotlin.String) : ApiResponse<ProductResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = retrieveProductRequestConfig(id = id)

        return@withContext request<Unit, ProductResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation retrieveProduct
     *
     * @param id The unique identifier of the product
     * @return RequestConfig
     */
    fun retrieveProductRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/canary/products/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/canary/products/{id}
     * Update Product
     * Updates a product&#39;s name, description, or metadata.
     * @param id The unique identifier of the product
     * @param updateProductDto Product update details
     * @return ProductResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateProduct(id: kotlin.String, updateProductDto: UpdateProductDto) : ProductResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = updateProductWithHttpInfo(id = id, updateProductDto = updateProductDto)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ProductResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/canary/products/{id}
     * Update Product
     * Updates a product&#39;s name, description, or metadata.
     * @param id The unique identifier of the product
     * @param updateProductDto Product update details
     * @return ApiResponse<ProductResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateProductWithHttpInfo(id: kotlin.String, updateProductDto: UpdateProductDto) : ApiResponse<ProductResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateProductRequestConfig(id = id, updateProductDto = updateProductDto)

        return@withContext request<UpdateProductDto, ProductResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateProduct
     *
     * @param id The unique identifier of the product
     * @param updateProductDto Product update details
     * @return RequestConfig
     */
    fun updateProductRequestConfig(id: kotlin.String, updateProductDto: UpdateProductDto) : RequestConfig<UpdateProductDto> {
        val localVariableBody = updateProductDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/canary/products/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
