/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.cashful.model.CreatePurchaseDto
import com.cashful.model.ErrorResponseDto
import com.cashful.model.PurchaseResponseDto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.cashful.infrastructure.ApiClient
import com.cashful.infrastructure.ApiResponse
import com.cashful.infrastructure.ClientException
import com.cashful.infrastructure.ClientError
import com.cashful.infrastructure.ServerException
import com.cashful.infrastructure.ServerError
import com.cashful.infrastructure.MultiValueMap
import com.cashful.infrastructure.PartConfig
import com.cashful.infrastructure.RequestConfig
import com.cashful.infrastructure.RequestMethod
import com.cashful.infrastructure.ResponseType
import com.cashful.infrastructure.Success
import com.cashful.infrastructure.toMultiValue

class PurchasesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.cashful.africa")
        }
    }

    /**
     * POST /api/canary/purchases
     * Buy with Cash Balance
     * (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
     * @param createPurchaseDto Purchase details
     * @return PurchaseResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createPurchase(createPurchaseDto: CreatePurchaseDto) : PurchaseResponseDto = withContext(Dispatchers.IO) {
        val localVarResponse = createPurchaseWithHttpInfo(createPurchaseDto = createPurchaseDto)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PurchaseResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/canary/purchases
     * Buy with Cash Balance
     * (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
     * @param createPurchaseDto Purchase details
     * @return ApiResponse<PurchaseResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createPurchaseWithHttpInfo(createPurchaseDto: CreatePurchaseDto) : ApiResponse<PurchaseResponseDto?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createPurchaseRequestConfig(createPurchaseDto = createPurchaseDto)

        return@withContext request<CreatePurchaseDto, PurchaseResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createPurchase
     *
     * @param createPurchaseDto Purchase details
     * @return RequestConfig
     */
    fun createPurchaseRequestConfig(createPurchaseDto: CreatePurchaseDto) : RequestConfig<CreatePurchaseDto> {
        val localVariableBody = createPurchaseDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/canary/purchases",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
