/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name The name of the user
 * @param email The email address of the user
 * @param password The password for the user account
 * @param role Optional role to assign to user
 * @param emailVerified Whether the user should be verified by default
 */
@Serializable

data class AdminCreateUserDto (

    /* The name of the user */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The email address of the user */
    @SerialName(value = "email")
    val email: kotlin.String,

    /* The password for the user account */
    @SerialName(value = "password")
    val password: kotlin.String,

    /* Optional role to assign to user */
    @SerialName(value = "role")
    val role: kotlin.String? = null,

    /* Whether the user should be verified by default */
    @SerialName(value = "emailVerified")
    val emailVerified: kotlin.Boolean? = null

) {


}

