/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param sessionId 
 * @param paymentIntentId 
 * @param iveriParams 
 * @param iVeri3dsEndpoint 
 * @param sandboxMode 
 * @param status 
 * @param transactionId 
 * @param authCode 
 * @param amount 
 * @param currency 
 * @param reason 
 */
@Serializable

data class CheckoutSessionConfirmResponseDto (

    @SerialName(value = "sessionId")
    val sessionId: kotlin.String,

    @SerialName(value = "paymentIntentId")
    val paymentIntentId: kotlin.String,

    @Contextual @SerialName(value = "iveriParams")
    val iveriParams: kotlin.Any? = null,

    @SerialName(value = "iVeri3dsEndpoint")
    val iVeri3dsEndpoint: kotlin.String? = null,

    @SerialName(value = "sandboxMode")
    val sandboxMode: kotlin.Boolean? = null,

    @SerialName(value = "status")
    val status: CheckoutSessionConfirmResponseDto.Status? = null,

    @SerialName(value = "transactionId")
    val transactionId: kotlin.String? = null,

    @SerialName(value = "authCode")
    val authCode: kotlin.String? = null,

    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal? = null,

    @SerialName(value = "currency")
    val currency: kotlin.String? = null,

    @SerialName(value = "reason")
    val reason: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: succeeded,failed
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "succeeded") succeeded("succeeded"),
        @SerialName(value = "failed") failed("failed");
    }

}

