/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import com.cashful.model.HostedCheckoutConfigDto
import com.cashful.model.LineItemDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param merchantId The ID of the merchant for the checkout session.
 * @param currency The three-letter ISO 4217 currency code
 * @param metadata Optional custom metadata
 * @param customerId The unique identifier of the customer
 * @param productId The unique identifier of the product
 * @param successUrl The URL to redirect to on successful payment
 * @param cancelUrl The URL to redirect to on cancel
 * @param lineItems Array of line items for the checkout
 * @param totalAmount The total amount in the smallest currency unit
 * @param mode The checkout mode (e.g., 'payment')
 * @param hostedCheckoutConfig Configuration for the hosted checkout page
 */
@Serializable

data class CreateCheckoutSessionDto (

    /* The ID of the merchant for the checkout session. */
    @SerialName(value = "merchantId")
    val merchantId: kotlin.String,

    /* The three-letter ISO 4217 currency code */
    @SerialName(value = "currency")
    val currency: kotlin.String,

    /* Optional custom metadata */
    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* The unique identifier of the customer */
    @SerialName(value = "customerId")
    val customerId: kotlin.String? = null,

    /* The unique identifier of the product */
    @SerialName(value = "productId")
    val productId: kotlin.String? = null,

    /* The URL to redirect to on successful payment */
    @SerialName(value = "successUrl")
    val successUrl: kotlin.String? = null,

    /* The URL to redirect to on cancel */
    @SerialName(value = "cancelUrl")
    val cancelUrl: kotlin.String? = null,

    /* Array of line items for the checkout */
    @SerialName(value = "lineItems")
    val lineItems: kotlin.collections.List<LineItemDto>? = null,

    /* The total amount in the smallest currency unit */
    @Contextual @SerialName(value = "totalAmount")
    val totalAmount: java.math.BigDecimal? = null,

    /* The checkout mode (e.g., 'payment') */
    @SerialName(value = "mode")
    val mode: kotlin.String? = null,

    /* Configuration for the hosted checkout page */
    @SerialName(value = "hostedCheckoutConfig")
    val hostedCheckoutConfig: HostedCheckoutConfigDto? = null

) {


}

