/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param merchantId Merchant ID associated with the event
 * @param type Event type identifier (e.g., 'checkout.loaded')
 * @param `data` Event payload data
 * @param relatedEntityId ID of the related entity
 * @param relatedEntityType Type of the related entity
 */
@Serializable

data class CreateEventDto (

    /* Merchant ID associated with the event */
    @SerialName(value = "merchantId")
    val merchantId: kotlin.String,

    /* Event type identifier (e.g., 'checkout.loaded') */
    @SerialName(value = "type")
    val type: kotlin.String,

    /* Event payload data */
    @Contextual @SerialName(value = "data")
    val `data`: kotlin.Any,

    /* ID of the related entity */
    @SerialName(value = "relatedEntityId")
    val relatedEntityId: kotlin.String? = null,

    /* Type of the related entity */
    @SerialName(value = "relatedEntityType")
    val relatedEntityType: kotlin.String? = null

) {


}

