/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param daily New customers in the last 24 hours
 * @param weekly New customers in the last 7 days
 * @param monthly New customers in the last 30 days
 */
@Serializable

data class CustomerStatsDto (

    /* New customers in the last 24 hours */
    @Contextual @SerialName(value = "daily")
    val daily: java.math.BigDecimal,

    /* New customers in the last 7 days */
    @Contextual @SerialName(value = "weekly")
    val weekly: java.math.BigDecimal,

    /* New customers in the last 30 days */
    @Contextual @SerialName(value = "monthly")
    val monthly: java.math.BigDecimal

) {


}

