/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param keyId The ID of the API key to delete
 */
@Serializable

data class DeleteApiKeyDto (

    /* The ID of the API key to delete */
    @SerialName(value = "keyId")
    val keyId: kotlin.String

) {


}

