/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param amount The amount for this line item in the smallest currency unit
 * @param currency The three-letter ISO 4217 currency code
 * @param name The name of the line item
 * @param productId The unique identifier of the product
 * @param quantity The quantity of the product
 * @param imageId The image identifier for the line item
 * @param imageUrl The URL of the image for the line item
 */
@Serializable

data class LineItemDto (

    /* The amount for this line item in the smallest currency unit */
    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal,

    /* The three-letter ISO 4217 currency code */
    @SerialName(value = "currency")
    val currency: kotlin.String,

    /* The name of the line item */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* The unique identifier of the product */
    @SerialName(value = "productId")
    val productId: kotlin.String? = null,

    /* The quantity of the product */
    @Contextual @SerialName(value = "quantity")
    val quantity: java.math.BigDecimal? = null,

    /* The image identifier for the line item */
    @SerialName(value = "imageId")
    val imageId: kotlin.String? = null,

    /* The URL of the image for the line item */
    @SerialName(value = "imageUrl")
    val imageUrl: kotlin.String? = null

) {


}

