/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique identifier
 * @param accountId Account ID
 * @param providerId Provider ID (e.g., google, github)
 * @param userId User ID
 * @param createdAt Creation timestamp
 * @param updatedAt Last update timestamp
 * @param accessToken Access token
 * @param refreshToken Refresh token
 * @param idToken ID token
 * @param accessTokenExpiresAt Access token expires at
 * @param refreshTokenExpiresAt Refresh token expires at
 * @param scope Scope
 * @param password Password
 */
@Serializable

data class LinkedAccountDto (

    /* Unique identifier */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* Account ID */
    @SerialName(value = "accountId")
    val accountId: kotlin.String,

    /* Provider ID (e.g., google, github) */
    @SerialName(value = "providerId")
    val providerId: kotlin.String,

    /* User ID */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    /* Creation timestamp */
    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* Last update timestamp */
    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    /* Access token */
    @SerialName(value = "accessToken")
    val accessToken: kotlin.String? = null,

    /* Refresh token */
    @SerialName(value = "refreshToken")
    val refreshToken: kotlin.String? = null,

    /* ID token */
    @SerialName(value = "idToken")
    val idToken: kotlin.String? = null,

    /* Access token expires at */
    @Contextual @SerialName(value = "accessTokenExpiresAt")
    val accessTokenExpiresAt: java.time.OffsetDateTime? = null,

    /* Refresh token expires at */
    @Contextual @SerialName(value = "refreshTokenExpiresAt")
    val refreshTokenExpiresAt: java.time.OffsetDateTime? = null,

    /* Scope */
    @SerialName(value = "scope")
    val scope: kotlin.String? = null,

    /* Password */
    @SerialName(value = "password")
    val password: kotlin.String? = null

) {


}

