/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param provider The social provider to link
 * @param accessToken Access token from provider
 * @param refreshToken Refresh token from provider
 * @param idToken ID token from provider
 * @param expiresAt Token expiration time
 */
@Serializable

data class LinkSocialDto (

    /* The social provider to link */
    @SerialName(value = "provider")
    val provider: kotlin.String,

    /* Access token from provider */
    @SerialName(value = "accessToken")
    val accessToken: kotlin.String? = null,

    /* Refresh token from provider */
    @SerialName(value = "refreshToken")
    val refreshToken: kotlin.String? = null,

    /* ID token from provider */
    @SerialName(value = "idToken")
    val idToken: kotlin.String? = null,

    /* Token expiration time */
    @Contextual @SerialName(value = "expiresAt")
    val expiresAt: java.math.BigDecimal? = null

) {


}

