/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param accounts List of linked social accounts
 */
@Serializable

data class ListAccountsResponseDto (

    /* List of linked social accounts */
    @SerialName(value = "accounts")
    val accounts: kotlin.collections.List<@Contextual kotlin.Any>

) {


}

