/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import com.cashful.model.PaginationResponseDto
import com.cashful.model.PaymentIntentResponseDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `data` List of payment intents
 * @param pagination Pagination metadata
 */
@Serializable

data class ListPaymentIntentsResponseDto (

    /* List of payment intents */
    @SerialName(value = "data")
    val `data`: kotlin.collections.List<PaymentIntentResponseDto>,

    /* Pagination metadata */
    @SerialName(value = "pagination")
    val pagination: PaginationResponseDto

) {


}

