/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Member ID
 * @param userId User ID
 * @param organizationId Organization ID
 * @param role Member role
 * @param createdAt Member creation date
 */
@Serializable

data class MemberDto (

    /* Member ID */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* User ID */
    @SerialName(value = "userId")
    val userId: kotlin.String,

    /* Organization ID */
    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    /* Member role */
    @SerialName(value = "role")
    val role: kotlin.String,

    /* Member creation date */
    @SerialName(value = "createdAt")
    val createdAt: kotlin.String

) {


}

