/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique identifier
 * @param createdAt 
 * @param updatedAt 
 * @param organizationId 
 * @param deletedAt 
 * @param companyRegistrationName 
 * @param companyRegistrationNumber 
 * @param companyTradingName 
 * @param vatRegistrationNumber 
 * @param industry 
 * @param subIndustry 
 * @param estimatedAnnualTurnover 
 * @param businessDescription 
 * @param companyMobileMoneySettlementNumber 
 * @param companyEmail 
 * @param companyContactNumber 
 * @param website 
 * @param socialMedia 
 * @param accountContactNumber 
 * @param customerSupportContactNumber 
 * @param customerSupportEscalationContactNumber 
 * @param emergencyContactNumber 
 * @param streetAddress 
 * @param apartment 
 * @param suburb 
 * @param city 
 * @param postalCode 
 * @param country 
 * @param bank 
 * @param accountType 
 * @param accountName 
 * @param accountNumber 
 * @param branchCode 
 * @param swiftCode 
 * @param certificateOfIncorporation 
 * @param identityDocuments 
 * @param bankAccountConfirmationLetter 
 * @param proofOfBusinessAddress 
 * @param termsAccepted 
 * @param acceptedAt 
 * @param currentStep 
 * @param status 
 * @param isCompleted 
 * @param completionScore 
 */
@Serializable

data class OrganizationComplianceResponseDto (

    /* Unique identifier */
    @SerialName(value = "id")
    val id: kotlin.String,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "organizationId")
    val organizationId: kotlin.String,

    @Contextual @SerialName(value = "deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "companyRegistrationName")
    val companyRegistrationName: kotlin.String? = null,

    @SerialName(value = "companyRegistrationNumber")
    val companyRegistrationNumber: kotlin.String? = null,

    @SerialName(value = "companyTradingName")
    val companyTradingName: kotlin.String? = null,

    @SerialName(value = "vatRegistrationNumber")
    val vatRegistrationNumber: kotlin.String? = null,

    @SerialName(value = "industry")
    val industry: kotlin.String? = null,

    @SerialName(value = "subIndustry")
    val subIndustry: kotlin.String? = null,

    @SerialName(value = "estimatedAnnualTurnover")
    val estimatedAnnualTurnover: kotlin.String? = null,

    @SerialName(value = "businessDescription")
    val businessDescription: kotlin.String? = null,

    @SerialName(value = "companyMobileMoneySettlementNumber")
    val companyMobileMoneySettlementNumber: kotlin.String? = null,

    @SerialName(value = "companyEmail")
    val companyEmail: kotlin.String? = null,

    @SerialName(value = "companyContactNumber")
    val companyContactNumber: kotlin.String? = null,

    @SerialName(value = "website")
    val website: kotlin.String? = null,

    @SerialName(value = "socialMedia")
    val socialMedia: kotlin.String? = null,

    @SerialName(value = "accountContactNumber")
    val accountContactNumber: kotlin.String? = null,

    @SerialName(value = "customerSupportContactNumber")
    val customerSupportContactNumber: kotlin.String? = null,

    @SerialName(value = "customerSupportEscalationContactNumber")
    val customerSupportEscalationContactNumber: kotlin.String? = null,

    @SerialName(value = "emergencyContactNumber")
    val emergencyContactNumber: kotlin.String? = null,

    @SerialName(value = "streetAddress")
    val streetAddress: kotlin.String? = null,

    @SerialName(value = "apartment")
    val apartment: kotlin.String? = null,

    @SerialName(value = "suburb")
    val suburb: kotlin.String? = null,

    @SerialName(value = "city")
    val city: kotlin.String? = null,

    @SerialName(value = "postalCode")
    val postalCode: kotlin.String? = null,

    @SerialName(value = "country")
    val country: kotlin.String? = null,

    @SerialName(value = "bank")
    val bank: kotlin.String? = null,

    @SerialName(value = "accountType")
    val accountType: kotlin.String? = null,

    @SerialName(value = "accountName")
    val accountName: kotlin.String? = null,

    @SerialName(value = "accountNumber")
    val accountNumber: kotlin.String? = null,

    @SerialName(value = "branchCode")
    val branchCode: kotlin.String? = null,

    @SerialName(value = "swiftCode")
    val swiftCode: kotlin.String? = null,

    @SerialName(value = "certificateOfIncorporation")
    val certificateOfIncorporation: kotlin.String? = null,

    @SerialName(value = "identityDocuments")
    val identityDocuments: kotlin.String? = null,

    @SerialName(value = "bankAccountConfirmationLetter")
    val bankAccountConfirmationLetter: kotlin.String? = null,

    @SerialName(value = "proofOfBusinessAddress")
    val proofOfBusinessAddress: kotlin.String? = null,

    @SerialName(value = "termsAccepted")
    val termsAccepted: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "acceptedAt")
    val acceptedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "currentStep")
    val currentStep: OrganizationComplianceResponseDto.CurrentStep? = null,

    @SerialName(value = "status")
    val status: OrganizationComplianceResponseDto.Status? = null,

    @SerialName(value = "isCompleted")
    val isCompleted: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "completionScore")
    val completionScore: java.math.BigDecimal? = null

) {

    /**
     * 
     *
     * Values: initiation,verification,business_details,banking_details,upload_documents,sign_agreement
     */
    @Serializable
    enum class CurrentStep(val value: kotlin.String) {
        @SerialName(value = "initiation") initiation("initiation"),
        @SerialName(value = "verification") verification("verification"),
        @SerialName(value = "business_details") business_details("business_details"),
        @SerialName(value = "banking_details") banking_details("banking_details"),
        @SerialName(value = "upload_documents") upload_documents("upload_documents"),
        @SerialName(value = "sign_agreement") sign_agreement("sign_agreement");
    }
    /**
     * 
     *
     * Values: pending,verified,rejected
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "pending") pending("pending"),
        @SerialName(value = "verified") verified("verified"),
        @SerialName(value = "rejected") rejected("rejected");
    }

}

