/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import com.cashful.model.HostedCheckoutConfigDto
import com.cashful.model.LineItemDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param merchantId 
 * @param url 
 * @param totalAmount 
 * @param currency 
 * @param mode 
 * @param active 
 * @param successUrl 
 * @param cancelUrl 
 * @param metadata 
 * @param createdAt 
 * @param updatedAt 
 * @param name 
 * @param description 
 * @param lineItems 
 * @param customerId 
 * @param hostedCheckoutConfig Configuration for the hosted checkout page
 * @param deletedAt 
 */
@Serializable

data class PaymentLinkResponseDto (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "merchantId")
    val merchantId: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    @Contextual @SerialName(value = "totalAmount")
    val totalAmount: java.math.BigDecimal,

    @SerialName(value = "currency")
    val currency: kotlin.String,

    @SerialName(value = "mode")
    val mode: PaymentLinkResponseDto.Mode,

    @SerialName(value = "active")
    val active: kotlin.Boolean,

    @SerialName(value = "successUrl")
    val successUrl: kotlin.String,

    @SerialName(value = "cancelUrl")
    val cancelUrl: kotlin.String,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "lineItems")
    val lineItems: kotlin.collections.List<LineItemDto>? = null,

    @SerialName(value = "customerId")
    val customerId: kotlin.String? = null,

    /* Configuration for the hosted checkout page */
    @SerialName(value = "hostedCheckoutConfig")
    val hostedCheckoutConfig: HostedCheckoutConfigDto? = null,

    @Contextual @SerialName(value = "deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: payment,setup,subscription
     */
    @Serializable
    enum class Mode(val value: kotlin.String) {
        @SerialName(value = "payment") payment("payment"),
        @SerialName(value = "setup") setup("setup"),
        @SerialName(value = "subscription") subscription("subscription");
    }

}

