/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param merchantId 
 * @param amount 
 * @param currency 
 * @param status 
 * @param metadata 
 * @param createdAt 
 * @param updatedAt 
 * @param bankAccount 
 * @param description 
 */
@Serializable

data class PayoutResponseDto (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "merchantId")
    val merchantId: kotlin.String,

    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal,

    @SerialName(value = "currency")
    val currency: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "bankAccount")
    val bankAccount: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {


}

