/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import com.cashful.model.SessionUserDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param token New access token
 * @param user User information
 * @param refreshToken New refresh token
 */
@Serializable

data class RefreshTokenResponseDto (

    /* New access token */
    @SerialName(value = "token")
    val token: kotlin.String,

    /* User information */
    @SerialName(value = "user")
    val user: SessionUserDto,

    /* New refresh token */
    @SerialName(value = "refreshToken")
    val refreshToken: kotlin.String? = null

) {


}

