/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param phoneNumber The phone number
 * @param code The OTP code received
 * @param newPassword The new password
 */
@Serializable

data class ResetPhonePasswordDto (

    /* The phone number */
    @SerialName(value = "phoneNumber")
    val phoneNumber: kotlin.String,

    /* The OTP code received */
    @SerialName(value = "code")
    val code: kotlin.String,

    /* The new password */
    @SerialName(value = "newPassword")
    val newPassword: kotlin.String

) {


}

