/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param newPassword The new password to set
 * @param token The token to reset password
 */
@Serializable

data class ResetPasswordDto (

    /* The new password to set */
    @SerialName(value = "newPassword")
    val newPassword: kotlin.String,

    /* The token to reset password */
    @SerialName(value = "token")
    val token: kotlin.String? = null

) {


}

