/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email Email message ID
 * @param sms SMS message ID
 */
@Serializable

data class SendMultiChannelNotification200Response (

    /* Email message ID */
    @SerialName(value = "email")
    val email: kotlin.String? = null,

    /* SMS message ID */
    @SerialName(value = "sms")
    val sms: kotlin.String? = null

) {


}

