/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import com.cashful.model.SessionUserDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param user User object
 * @param token Session token
 * @param redirect Whether to redirect
 * @param url Redirect URL
 */
@Serializable

data class SignInResponseDto (

    /* User object */
    @SerialName(value = "user")
    val user: SessionUserDto,

    /* Session token */
    @SerialName(value = "token")
    val token: kotlin.String,

    /* Whether to redirect */
    @SerialName(value = "redirect")
    val redirect: SignInResponseDto.Redirect?,

    /* Redirect URL */
    @SerialName(value = "url")
    val url: kotlin.String? = null

) {

    /**
     * Whether to redirect
     *
     * Values: 
     */
    @Serializable
    enum class Redirect(val value: java.math.BigDecimal) {
    }

}

