/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import com.cashful.model.SessionUserDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param user User object created successfully
 * @param token Authentication token for the session
 */
@Serializable

data class SignUpResponseDto (

    /* User object created successfully */
    @SerialName(value = "user")
    val user: SessionUserDto,

    /* Authentication token for the session */
    @SerialName(value = "token")
    val token: kotlin.String? = null

) {


}

