/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cashful.model

import com.cashful.model.HostedCheckoutConfigDto

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status 
 * @param metadata Optional custom metadata
 * @param successUrl The URL to redirect to on successful payment
 * @param failureUrl The URL to redirect to on failure
 * @param cancelUrl The URL to redirect to on cancel
 * @param hostedCheckoutConfig Configuration for the hosted checkout page
 */
@Serializable

data class UpdateCheckoutSessionDto (

    @SerialName(value = "status")
    val status: kotlin.String,

    /* Optional custom metadata */
    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* The URL to redirect to on successful payment */
    @SerialName(value = "successUrl")
    val successUrl: kotlin.String? = null,

    /* The URL to redirect to on failure */
    @SerialName(value = "failureUrl")
    val failureUrl: kotlin.String? = null,

    /* The URL to redirect to on cancel */
    @SerialName(value = "cancelUrl")
    val cancelUrl: kotlin.String? = null,

    /* Configuration for the hosted checkout page */
    @SerialName(value = "hostedCheckoutConfig")
    val hostedCheckoutConfig: HostedCheckoutConfigDto? = null

) {


}

